// FOUNDATION LEVEL 08 - one schema, compiled by two different toolchains.
//
// This exact file is fed to BOTH `protoc` (the official C++ compiler) and
// `buf generate` (the modern wrapper). Neither one invents anything: both
// shell out to the same protoc-gen-go / Python codegen plugins, so the
// generated code - and therefore the encoded bytes - come out identical.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: l08_toolchains.proto

package l08

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Labels        []string               `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_l08_toolchains_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_l08_toolchains_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_l08_toolchains_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Metric) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_l08_toolchains_proto protoreflect.FileDescriptor

const file_l08_toolchains_proto_rawDesc = "" +
	"\n" +
	"\x14l08_toolchains.proto\x12\tfound.l08\"J\n" +
	"\x06Metric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x16\n" +
	"\x06labels\x18\x03 \x03(\tR\x06labelsB7Z5dsapractice/api/Protobuf/Foundation/golang/pb/l08;l08b\x06proto3"

var (
	file_l08_toolchains_proto_rawDescOnce sync.Once
	file_l08_toolchains_proto_rawDescData []byte
)

func file_l08_toolchains_proto_rawDescGZIP() []byte {
	file_l08_toolchains_proto_rawDescOnce.Do(func() {
		file_l08_toolchains_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_l08_toolchains_proto_rawDesc), len(file_l08_toolchains_proto_rawDesc)))
	})
	return file_l08_toolchains_proto_rawDescData
}

var file_l08_toolchains_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_l08_toolchains_proto_goTypes = []any{
	(*Metric)(nil), // 0: found.l08.Metric
}
var file_l08_toolchains_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_l08_toolchains_proto_init() }
func file_l08_toolchains_proto_init() {
	if File_l08_toolchains_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_l08_toolchains_proto_rawDesc), len(file_l08_toolchains_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_l08_toolchains_proto_goTypes,
		DependencyIndexes: file_l08_toolchains_proto_depIdxs,
		MessageInfos:      file_l08_toolchains_proto_msgTypes,
	}.Build()
	File_l08_toolchains_proto = out.File
	file_l08_toolchains_proto_goTypes = nil
	file_l08_toolchains_proto_depIdxs = nil
}
