apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        # Nginx forwards traffic to http://backend-svc
        # The ClusterIP service handles load balancing across the 2 backend pods
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: NodePort # Exposes port to the outside world
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080 
