/*
FOUNDATION LEVEL 08 - protoc and buf produce the exact same bytes
==================================================================
`protoc` is the original compiler. `buf` is a modern alternative that wraps
the exact same plugin ecosystem but solves the UX and governance problems:

  protoc                                    buf
  -----------------------------------------------------------------------------
  every include path and input file on      the schema is declared once in
  the command line, every time              buf.yaml and checked in
  plugin flags memorised or buried in       plugin config declared in
  a Makefile                                buf.gen.yaml, reproducible in CI
  imports resolved from your filesystem     dependencies resolved and version-
  (vendor other people's protos by hand)    pinned from a registry
  no opinion on schema quality              `buf lint` enforces conventions
  no protection against rule 2 of           `buf breaking` diffs against the
  level 06                                  last release and FAILS the build

That last row is the one that makes teams switch.

You will learn
  * that both toolchains call the SAME codegen plugins, so neither owns the format
  * PROOF: buf-generated code is source-identical to protoc-generated code
    except for the compiler version comment
  * that a .proto is a portable asset, not a protoc artefact

Run it   go run ./Protobuf/Foundation/golang/08_protoc_and_buf_same_bytes
*/
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"google.golang.org/protobuf/proto"

	"dsapractice/api/Protobuf/Foundation/golang/pb/l08"
)

func must(ok bool, what string) {
	if !ok {
		panic("FAILED: " + what)
	}
}

// Expected byte format
const expectedHex = "0a086370752e6c6f616411000000000000e83f1a06686f73743d611a08656e763d70726f64"

func main() {
	fmt.Println("== 1. encode with the protoc-generated code ==")
	metric := &l08.Metric{
		Name:   "cpu.load",
		Value:  0.75,
		Labels: []string{"host=a", "env=prod"},
	}
	
	protocBytes, err := proto.Marshal(metric)
	must(err == nil, "marshal")
	protocHex := fmt.Sprintf("%x", protocBytes)
	
	fmt.Printf("  Metric{Name: \"cpu.load\", Value: 0.75, Labels: [host=a, env=prod]}\n")
	fmt.Printf("  %d bytes: %s\n", len(protocBytes), protocHex)
	must(protocHex == expectedHex, "protoc output matches expectation")

	fmt.Println("\n== 2. compare the generated Go source files ==")
	// Find the workspace root based on the current directory
	cwd, _ := os.Getwd()
	// Navigate up to API/Protobuf/Foundation
	baseDir := filepath.Dir(cwd) 
	
	protocFile := filepath.Join(baseDir, "golang", "pb", "l08", "l08_toolchains.pb.go")
	bufFile := filepath.Join(baseDir, "buf_out", "golang", "pb", "l08", "l08_toolchains.pb.go")

	bufContent, err := os.ReadFile(bufFile)
	if err != nil {
		fmt.Printf("  SKIPPED: %s is missing.\n", bufFile)
		fmt.Println("  Install buf and re-run generate.sh to enable this half:")
		fmt.Println("      go install github.com/bufbuild/buf/cmd/buf@latest")
		fmt.Println("\nOK")
		return
	}

	protocContent, err := os.ReadFile(protocFile)
	must(err == nil, "read protoc generated file")

	fmt.Printf("  protoc output size: %d bytes\n", len(protocContent))
	fmt.Printf("  buf output size:    %d bytes\n", len(bufContent))
	
	// Strip the protoc version comment which differs because buf proxies the plugin
	// protoc-gen-go writes: "// \tprotoc        v..."
	// buf-gen-go writes:    "// \tprotoc        (unknown)"
	pStr := strings.Split(string(protocContent), "// \tprotoc")
	bStr := strings.Split(string(bufContent), "// \tprotoc")
	
	must(len(pStr) == 2 && len(bStr) == 2, "found protoc version string")
	
	pTail := strings.SplitN(pStr[1], "\n", 2)[1]
	bTail := strings.SplitN(bStr[1], "\n", 2)[1]
	
	must(pStr[0] == bStr[0], "header matches")
	must(pTail == bTail, "body matches")

	fmt.Println("\n== 3. THE PROOF ==")
	fmt.Println("  The Go source files generated by protoc and buf are BYTE-FOR-BYTE IDENTICAL,")
	fmt.Println("  except for the compiler version comment ('vX.Y' vs '(unknown)').")
	fmt.Println("  This is because both toolchains invoke the EXACT SAME 'protoc-gen-go' plugin.")
	fmt.Println("  Neither toolchain owns the wire format or the struct layout. The .proto file does.")

	fmt.Println("\n== 4. what buf adds that protoc cannot ==")
	fmt.Println("  ../buf.yaml declares the schema once, so `buf generate` needs no flags:")
	fmt.Println("      protoc -I proto --go_out=. --go_opt=module=... proto/*.proto")
	fmt.Println("      buf generate")
	fmt.Println("  and it unlocks two commands protoc has no equivalent for:")
	fmt.Println("      buf lint      - enforce naming/structure conventions across the repo")
	fmt.Println("      buf breaking  - diff this schema against the last released version")
	fmt.Println("                      and FAIL if any change from level 06's breaking list")
	fmt.Println("                      slipped in (renumbered field, changed type, reused tag)")
	fmt.Println("  Try it:  cd .. && buf lint && buf breaking --against '.git#branch=main'")
	fmt.Println("  That is the real reason to adopt buf. Not different bytes - the same")
	fmt.Println("  bytes, with rule 2 of level 06 enforced by CI instead of by memory.")

	fmt.Println("\nOK")
}
