"""
24 - gRPC service - Reference Solution
==========================================

See `24_grpc_service_explanation.py` for the full spec, rationale, and
acceptance criteria. See `task_service.proto` for the protobuf/gRPC
schema and the exact `grpc_tools.protoc` generation command.
"""

from __future__ import annotations

import asyncio
import uuid
from collections.abc import AsyncIterator, Awaitable, Callable
from typing import Any

import grpc  # type: ignore[import-untyped]

# Generated by `python -m grpc_tools.protoc` from task_service.proto (see
# that file's header comment for the exact command). mypy has no stub/type
# information for generated protobuf/gRPC modules, so the ignore is scoped
# to these two imports rather than disabling mypy for the file.
import task_service_pb2 as pb2  # type: ignore[import-untyped]
import task_service_pb2_grpc as pb2_grpc  # type: ignore[import-untyped]

# Polling granularity for SlowOperation's cooperative-cancellation loop.
_SLOW_OPERATION_STEP_SECONDS = 0.05


# ---------------------------------------------------------------------------
# Server: TaskServicer.
# ---------------------------------------------------------------------------
class TaskServicer(pb2_grpc.TaskServiceServicer):
    """In-memory implementation of `TaskService`.

    A single `grpc.aio` server runs every handler as a coroutine on one
    event loop, and dict mutation itself never awaits mid-operation, so
    `self._tasks` needs no extra lock: no other coroutine can observe a
    half-written dict, the same reasoning that makes plain Python dicts
    safe under cooperative (not preemptive) concurrency.
    """

    def __init__(self) -> None:
        self._tasks: dict[str, pb2.Task] = {}

    async def CreateTask(
        self, request: pb2.CreateTaskRequest, context: grpc.aio.ServicerContext
    ) -> pb2.Task:
        # Validation belongs in the handler, not the client's hands -
        # INVALID_ARGUMENT (not INTERNAL) tells a well-behaved client this
        # request will never succeed as-is, so it shouldn't blindly retry.
        if not request.title.strip():
            await context.abort(
                grpc.StatusCode.INVALID_ARGUMENT, "title must not be blank"
            )

        task = pb2.Task(id=uuid.uuid4().hex, title=request.title, done=False)
        self._tasks[task.id] = task
        return task

    async def GetTask(
        self, request: pb2.GetTaskRequest, context: grpc.aio.ServicerContext
    ) -> pb2.Task:
        task = self._tasks.get(request.id)
        if task is None:
            # NOT_FOUND, not INTERNAL: this is an expected, well-defined
            # outcome for a bad id, not a server malfunction - a client's
            # generic error handling should treat the two very differently.
            await context.abort(
                grpc.StatusCode.NOT_FOUND, f"task {request.id!r} not found"
            )
            # grpc's types aren't stub-available (see the import above), so
            # mypy can't see that context.abort() never returns; this makes
            # the "task is narrowed to non-None below" control flow explicit
            # for the type checker. Never reached at runtime.
            raise AssertionError("unreachable")
        return task

    async def ListTasks(
        self, request: pb2.ListTasksRequest, context: grpc.aio.ServicerContext
    ) -> AsyncIterator[pb2.Task]:
        # Server-streaming: a plain async generator. gRPC pulls from it
        # and writes each yielded message to the wire as it's produced -
        # no manual context.write() call needed in grpc.aio.
        for task in self._tasks.values():
            yield task

    async def SlowOperation(
        self, request: pb2.SlowRequest, context: grpc.aio.ServicerContext
    ) -> pb2.SlowResponse:
        elapsed = 0.0
        while elapsed < request.delay_seconds:
            # Cooperative cancellation: check before every sleep instead
            # of sleeping the full duration in one call. The moment the
            # client's deadline fires (or it cancels), context.cancelled()
            # flips true and this handler stops doing work nobody will
            # receive the result of.
            if context.cancelled():
                return pb2.SlowResponse()
            await asyncio.sleep(_SLOW_OPERATION_STEP_SECONDS)
            elapsed += _SLOW_OPERATION_STEP_SECONDS
        return pb2.SlowResponse(message=f"slept {request.delay_seconds}s")


# ---------------------------------------------------------------------------
# Interceptor: times every RPC without the servicer knowing.
# ---------------------------------------------------------------------------
class LoggingInterceptor(grpc.aio.ServerInterceptor):
    """Records `(method_path, duration_seconds)` for every completed RPC.

    Wraps unary-unary and unary-stream handlers generically by rebuilding
    the `RpcMethodHandler` gRPC gives back from `continuation` - the
    servicer methods themselves have no idea this interceptor exists,
    which is the entire point of putting cross-cutting concerns here
    instead of in every handler.
    """

    def __init__(self) -> None:
        self.calls: list[tuple[str, float]] = []

    async def intercept_service(
        self,
        continuation: Callable[[Any], Awaitable[Any]],
        handler_call_details: Any,
    ) -> Any:
        handler = await continuation(handler_call_details)
        if handler is None:
            # No such method - let the framework produce its own
            # UNIMPLEMENTED response; nothing for this interceptor to do.
            return handler

        method = handler_call_details.method

        if handler.unary_unary is not None:
            inner_unary = handler.unary_unary

            async def wrapped_unary_unary(request: Any, context: Any) -> Any:
                start = asyncio.get_event_loop().time()
                try:
                    return await inner_unary(request, context)
                finally:
                    # In a `finally`, not after a bare return: a raised or
                    # aborted call is exactly the kind of RPC you most
                    # want a timing/audit trail for.
                    self.calls.append((method, asyncio.get_event_loop().time() - start))

            return grpc.unary_unary_rpc_method_handler(
                wrapped_unary_unary,
                request_deserializer=handler.request_deserializer,
                response_serializer=handler.response_serializer,
            )

        if handler.unary_stream is not None:
            inner_stream = handler.unary_stream

            async def wrapped_unary_stream(request: Any, context: Any) -> Any:
                start = asyncio.get_event_loop().time()
                try:
                    async for response in inner_stream(request, context):
                        yield response
                finally:
                    self.calls.append((method, asyncio.get_event_loop().time() - start))

            return grpc.unary_stream_rpc_method_handler(
                wrapped_unary_stream,
                request_deserializer=handler.request_deserializer,
                response_serializer=handler.response_serializer,
            )

        # This service has no client-streaming/bidi-streaming methods;
        # pass anything else through untouched rather than guessing.
        return handler


# ---------------------------------------------------------------------------
# Server bootstrap.
# ---------------------------------------------------------------------------
async def serve(
    port: int = 0,
) -> tuple[grpc.aio.Server, int, TaskServicer, LoggingInterceptor]:
    interceptor = LoggingInterceptor()
    server = grpc.aio.server(interceptors=[interceptor])
    servicer = TaskServicer()
    pb2_grpc.add_TaskServiceServicer_to_server(servicer, server)

    # port=0 asks the OS for a free ephemeral port; add_insecure_port
    # returns the port actually bound, which is what callers need to
    # build a channel against.
    bound_port: int = server.add_insecure_port(f"[::]:{port}")
    await server.start()
    return server, bound_port, servicer, interceptor


# ---------------------------------------------------------------------------
# Best practices
# ---------------------------------------------------------------------------
# - `grpc.aio` over the legacy sync `grpc.server()` for any service whose
#   handlers do real I/O - it lets handlers `await` naturally instead of
#   blocking a thread-pool worker per in-flight RPC.
# - Put cross-cutting concerns (logging, auth, metrics) in interceptors,
#   not in every handler - the same argument as HTTP middleware, applied
#   to gRPC's handler-wrapping model. Time/log in a `finally` so failed
#   and aborted calls are captured too, not just successes.
# - Use `grpc.StatusCode` deliberately: `INVALID_ARGUMENT` for a request
#   that will never succeed as-is, `NOT_FOUND` for a well-defined missing
#   resource, `DEADLINE_EXCEEDED`/`UNAVAILABLE` for retryable conditions -
#   the code is part of the API contract, not an afterthought.
# - Check `context.cancelled()` periodically in any handler that might
#   run longer than a typical client deadline - it's the only way a
#   coroutine cooperatively notices its caller stopped waiting.
# - Always `await server.stop(grace_period)` (or `None` for immediate) to
#   shut a `grpc.aio` server down cleanly - an unstopped server leaves its
#   port bound and can leave pending tasks on interpreter shutdown.
#
# Alternative approaches
# -----------------------
# - The legacy sync `grpc.server()` with a `ThreadPoolExecutor` is still
#   the right choice for a CPU-bound or blocking-library-heavy service
#   that isn't already asyncio-based - forcing `grpc.aio` on top of
#   blocking handlers just reintroduces the blocking-the-loop problem
#   `asyncio` exists to avoid.
# - `grpcio-reflection` (adds a reflection service so `grpcurl`/`evans`
#   can introspect the service without the `.proto` file locally) and
#   `grpc-health-checking` (the standard `Health/Check` RPC used by load
#   balancers and Kubernetes) are common production add-ons not included
#   here to keep the example focused - problem 25's `/healthz`/`/readyz`
#   cover the same idea over HTTP instead.
# - Structured error details via `google.rpc.Status`/`error_details_pb2`
#   (richer than a status code + string) are available when a client
#   needs machine-readable error payloads beyond what `context.abort`'s
#   `(code, details)` pair provides.
