# ruff: noqa
# mypy: ignore-errors
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

import task_service_pb2 as task__service__pb2

GRPC_GENERATED_VERSION = "1.83.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in task_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class TaskServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTask = channel.unary_unary(
            "/pyengineering.tasks.TaskService/CreateTask",
            request_serializer=task__service__pb2.CreateTaskRequest.SerializeToString,
            response_deserializer=task__service__pb2.Task.FromString,
            _registered_method=True,
        )
        self.GetTask = channel.unary_unary(
            "/pyengineering.tasks.TaskService/GetTask",
            request_serializer=task__service__pb2.GetTaskRequest.SerializeToString,
            response_deserializer=task__service__pb2.Task.FromString,
            _registered_method=True,
        )
        self.ListTasks = channel.unary_stream(
            "/pyengineering.tasks.TaskService/ListTasks",
            request_serializer=task__service__pb2.ListTasksRequest.SerializeToString,
            response_deserializer=task__service__pb2.Task.FromString,
            _registered_method=True,
        )
        self.SlowOperation = channel.unary_unary(
            "/pyengineering.tasks.TaskService/SlowOperation",
            request_serializer=task__service__pb2.SlowRequest.SerializeToString,
            response_deserializer=task__service__pb2.SlowResponse.FromString,
            _registered_method=True,
        )


class TaskServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateTask(self, request, context):
        """Unary RPC. Returns INVALID_ARGUMENT (via context.abort) for a blank title."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetTask(self, request, context):
        """Unary RPC. Returns NOT_FOUND (via context.abort) for an unknown id -
        the error-model half of the exercise.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListTasks(self, request, context):
        """Server-streaming RPC: the streaming half of the exercise."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SlowOperation(self, request, context):
        """Unary RPC, deliberately slow - the deadline-propagation half of the
        exercise (see message comment above).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_TaskServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CreateTask": grpc.unary_unary_rpc_method_handler(
            servicer.CreateTask,
            request_deserializer=task__service__pb2.CreateTaskRequest.FromString,
            response_serializer=task__service__pb2.Task.SerializeToString,
        ),
        "GetTask": grpc.unary_unary_rpc_method_handler(
            servicer.GetTask,
            request_deserializer=task__service__pb2.GetTaskRequest.FromString,
            response_serializer=task__service__pb2.Task.SerializeToString,
        ),
        "ListTasks": grpc.unary_stream_rpc_method_handler(
            servicer.ListTasks,
            request_deserializer=task__service__pb2.ListTasksRequest.FromString,
            response_serializer=task__service__pb2.Task.SerializeToString,
        ),
        "SlowOperation": grpc.unary_unary_rpc_method_handler(
            servicer.SlowOperation,
            request_deserializer=task__service__pb2.SlowRequest.FromString,
            response_serializer=task__service__pb2.SlowResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "pyengineering.tasks.TaskService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "pyengineering.tasks.TaskService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class TaskService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateTask(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pyengineering.tasks.TaskService/CreateTask",
            task__service__pb2.CreateTaskRequest.SerializeToString,
            task__service__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetTask(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pyengineering.tasks.TaskService/GetTask",
            task__service__pb2.GetTaskRequest.SerializeToString,
            task__service__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListTasks(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/pyengineering.tasks.TaskService/ListTasks",
            task__service__pb2.ListTasksRequest.SerializeToString,
            task__service__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SlowOperation(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pyengineering.tasks.TaskService/SlowOperation",
            task__service__pb2.SlowRequest.SerializeToString,
            task__service__pb2.SlowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
