# ruff: noqa
# mypy: ignore-errors
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: task_service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 35, 1, "", "task_service.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12task_service.proto\x12\x13pyengineering.tasks"/\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04\x64one\x18\x03 \x01(\x08""\n\x11\x43reateTaskRequest\x12\r\n\x05title\x18\x01 \x01(\t"\x1c\n\x0eGetTaskRequest\x12\n\n\x02id\x18\x01 \x01(\t"\x12\n\x10ListTasksRequest"$\n\x0bSlowRequest\x12\x15\n\rdelay_seconds\x18\x01 \x01(\x01"\x1f\n\x0cSlowResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xd0\x02\n\x0bTaskService\x12O\n\nCreateTask\x12&.pyengineering.tasks.CreateTaskRequest\x1a\x19.pyengineering.tasks.Task\x12I\n\x07GetTask\x12#.pyengineering.tasks.GetTaskRequest\x1a\x19.pyengineering.tasks.Task\x12O\n\tListTasks\x12%.pyengineering.tasks.ListTasksRequest\x1a\x19.pyengineering.tasks.Task0\x01\x12T\n\rSlowOperation\x12 .pyengineering.tasks.SlowRequest\x1a!.pyengineering.tasks.SlowResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "task_service_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_TASK"]._serialized_start = 43
    _globals["_TASK"]._serialized_end = 90
    _globals["_CREATETASKREQUEST"]._serialized_start = 92
    _globals["_CREATETASKREQUEST"]._serialized_end = 126
    _globals["_GETTASKREQUEST"]._serialized_start = 128
    _globals["_GETTASKREQUEST"]._serialized_end = 156
    _globals["_LISTTASKSREQUEST"]._serialized_start = 158
    _globals["_LISTTASKSREQUEST"]._serialized_end = 176
    _globals["_SLOWREQUEST"]._serialized_start = 178
    _globals["_SLOWREQUEST"]._serialized_end = 214
    _globals["_SLOWRESPONSE"]._serialized_start = 216
    _globals["_SLOWRESPONSE"]._serialized_end = 247
    _globals["_TASKSERVICE"]._serialized_start = 250
    _globals["_TASKSERVICE"]._serialized_end = 586
# @@protoc_insertion_point(module_scope)
