// REAL-WORLD EXAMPLE: connectrpc.com/connect (External 2)
// Demonstrates: A modern alternative to standard gRPC that runs cleanly over net/http
// and natively supports gRPC, gRPC-Web, and Connect protocols out of the box.
package main

import (
	"context"
	"log"
	"net/http"

	// "connectrpc.com/connect"
	// userpb "path/to/userpb"
	// "path/to/userpb/userpbconnect"
)

// --- MOCK PROTOBUF TYPES ---
type GetUserRequest struct{ Id string }
type User struct{ Name string }
type GetUserResponse struct{ User *User }

// Mock Connect Types
type Request struct{ Msg *GetUserRequest }
type Response struct{ Msg *GetUserResponse }
// ---------------------------

type server struct{}

func (s *server) GetUser(ctx context.Context, req *Request) (*Response, error) {
	// Business logic
	res := &Response{
		Msg: &GetUserResponse{
			User: &User{Name: "Alice"},
		},
	}
	return res, nil
}

func main() {
	mux := http.NewServeMux()
	
	// In a real project, this is generated by Connect:
	// path, handler := userpbconnect.NewUserServiceHandler(&server{})
	// mux.Handle(path, handler)
	
	log.Println("Connect RPC Server running on :8080 (supports gRPC, gRPC-Web, and HTTP POST!)")
	http.ListenAndServe(":8080", mux)
}
