// FOUNDATION LEVEL 05 (the OLDER schema) - knows only three Status values.
// An older client that has not been redeployed yet uses this file, and will
// be handed STATUS_ARCHIVED (= 3) by the newer service.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: l05_old.proto

package l05old

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_QUEUED      Status = 1
	Status_STATUS_RUNNING     Status = 2 // STATUS_ARCHIVED = 3;  <- does not exist yet in this build
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_QUEUED",
		2: "STATUS_RUNNING",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_QUEUED":      1,
		"STATUS_RUNNING":     2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_l05_old_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_l05_old_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_l05_old_proto_rawDescGZIP(), []int{0}
}

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=found.l05.old.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_l05_old_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_l05_old_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_l05_old_proto_rawDescGZIP(), []int{0}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

var File_l05_old_proto protoreflect.FileDescriptor

const file_l05_old_proto_rawDesc = "" +
	"\n" +
	"\rl05_old.proto\x12\rfound.l05.old\"D\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.found.l05.old.StatusR\x06status*G\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATUS_QUEUED\x10\x01\x12\x12\n" +
	"\x0eSTATUS_RUNNING\x10\x02B=Z;dsapractice/api/Protobuf/Foundation/golang/pb/l05old;l05oldb\x06proto3"

var (
	file_l05_old_proto_rawDescOnce sync.Once
	file_l05_old_proto_rawDescData []byte
)

func file_l05_old_proto_rawDescGZIP() []byte {
	file_l05_old_proto_rawDescOnce.Do(func() {
		file_l05_old_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_l05_old_proto_rawDesc), len(file_l05_old_proto_rawDesc)))
	})
	return file_l05_old_proto_rawDescData
}

var file_l05_old_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_l05_old_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_l05_old_proto_goTypes = []any{
	(Status)(0), // 0: found.l05.old.Status
	(*Job)(nil), // 1: found.l05.old.Job
}
var file_l05_old_proto_depIdxs = []int32{
	0, // 0: found.l05.old.Job.status:type_name -> found.l05.old.Status
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_l05_old_proto_init() }
func file_l05_old_proto_init() {
	if File_l05_old_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_l05_old_proto_rawDesc), len(file_l05_old_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_l05_old_proto_goTypes,
		DependencyIndexes: file_l05_old_proto_depIdxs,
		EnumInfos:         file_l05_old_proto_enumTypes,
		MessageInfos:      file_l05_old_proto_msgTypes,
	}.Build()
	File_l05_old_proto = out.File
	file_l05_old_proto_goTypes = nil
	file_l05_old_proto_depIdxs = nil
}
