// FOUNDATION LEVEL 06 (schema version 2) - a SAFE evolution of l06_v1.proto.
//
// Three rules are visible in this file:
//   1. every field v1 had keeps its exact number and type   (1, 2, 3)
//   2. the new field gets a brand-new, never-before-used number (4)
//   3. a field that was deleted has its number AND name `reserved` forever,
//      so no future edit can silently recycle it

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: l06_v2.proto

package l06v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sku           string                 `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Qty           int32                  `protobuf:"varint,3,opt,name=qty,proto3" json:"qty,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"` // NEW in v2. v1 readers do not know it and must not break.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_l06_v2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_l06_v2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_l06_v2_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Order) GetQty() int32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *Order) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

var File_l06_v2_proto protoreflect.FileDescriptor

const file_l06_v2_proto_rawDesc = "" +
	"\n" +
	"\fl06_v2.proto\x12\ffound.l06.v2\"l\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\tR\x03sku\x12\x10\n" +
	"\x03qty\x18\x03 \x01(\x05R\x03qty\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrencyJ\x04\b\t\x10\n" +
	"R\rinternal_noteB;Z9dsapractice/api/Protobuf/Foundation/golang/pb/l06v2;l06v2b\x06proto3"

var (
	file_l06_v2_proto_rawDescOnce sync.Once
	file_l06_v2_proto_rawDescData []byte
)

func file_l06_v2_proto_rawDescGZIP() []byte {
	file_l06_v2_proto_rawDescOnce.Do(func() {
		file_l06_v2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_l06_v2_proto_rawDesc), len(file_l06_v2_proto_rawDesc)))
	})
	return file_l06_v2_proto_rawDescData
}

var file_l06_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_l06_v2_proto_goTypes = []any{
	(*Order)(nil), // 0: found.l06.v2.Order
}
var file_l06_v2_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_l06_v2_proto_init() }
func file_l06_v2_proto_init() {
	if File_l06_v2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_l06_v2_proto_rawDesc), len(file_l06_v2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_l06_v2_proto_goTypes,
		DependencyIndexes: file_l06_v2_proto_depIdxs,
		MessageInfos:      file_l06_v2_proto_msgTypes,
	}.Build()
	File_l06_v2_proto = out.File
	file_l06_v2_proto_goTypes = nil
	file_l06_v2_proto_depIdxs = nil
}
