# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: l01_v2.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'l01_v2.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cl01_v2.proto\x12\x0c\x66ound.l01.v2\"q\n\x04\x42ook\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04year\x18\x02 \x01(\x05\x12\x10\n\x08in_print\x18\x03 \x01(\x08\x12\r\n\x05price\x18\x04 \x01(\x01\x12\x13\n\x0b\x63opies_sold\x18\x05 \x01(\x03\x12\x17\n\x0f\x63over_thumbnail\x18\x06 \x01(\x0c\x42;Z9dsapractice/api/Protobuf/Foundation/golang/pb/l01v2;l01v2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'l01_v2_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9dsapractice/api/Protobuf/Foundation/golang/pb/l01v2;l01v2'
  _globals['_BOOK']._serialized_start=30
  _globals['_BOOK']._serialized_end=143
# @@protoc_insertion_point(module_scope)
