# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: l04_presence.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'l04_presence.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12l04_presence.proto\x12\tfound.l04\"Q\n\x07Reading\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63\x65lsius\x18\x02 \x01(\x05\x12\x15\n\x08humidity\x18\x03 \x01(\x05H\x00\x88\x01\x01\x42\x0b\n\t_humidityB7Z5dsapractice/api/Protobuf/Foundation/golang/pb/l04;l04b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'l04_presence_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5dsapractice/api/Protobuf/Foundation/golang/pb/l04;l04'
  _globals['_READING']._serialized_start=33
  _globals['_READING']._serialized_end=114
# @@protoc_insertion_point(module_scope)
