# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: l06_v2.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'l06_v2.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cl06_v2.proto\x12\x0c\x66ound.l06.v2\"T\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0b\n\x03sku\x18\x02 \x01(\t\x12\x0b\n\x03qty\x18\x03 \x01(\x05\x12\x10\n\x08\x63urrency\x18\x04 \x01(\tJ\x04\x08\t\x10\nR\rinternal_noteB;Z9dsapractice/api/Protobuf/Foundation/golang/pb/l06v2;l06v2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'l06_v2_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9dsapractice/api/Protobuf/Foundation/golang/pb/l06v2;l06v2'
  _globals['_ORDER']._serialized_start=30
  _globals['_ORDER']._serialized_end=114
# @@protoc_insertion_point(module_scope)
