# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: l07_oneof.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'l07_oneof.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fl07_oneof.proto\x12\tfound.l07\"i\n\x07Payment\x12\x14\n\x0c\x61mount_cents\x18\x01 \x01(\x03\x12\x14\n\ncard_token\x18\x02 \x01(\tH\x00\x12\x13\n\tbank_iban\x18\x03 \x01(\tH\x00\x12\x13\n\twallet_id\x18\x04 \x01(\tH\x00\x42\x08\n\x06methodB7Z5dsapractice/api/Protobuf/Foundation/golang/pb/l07;l07b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'l07_oneof_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5dsapractice/api/Protobuf/Foundation/golang/pb/l07;l07'
  _globals['_PAYMENT']._serialized_start=30
  _globals['_PAYMENT']._serialized_end=135
# @@protoc_insertion_point(module_scope)
