# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: l11_capstone.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'l11_capstone.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12l11_capstone.proto\x12\tfound.l11\"<\n\x07\x41\x64\x64ress\x12\r\n\x05line1\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\x14\n\x0c\x63ountry_code\x18\x03 \x01(\t\">\n\x08LineItem\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x0b\n\x03qty\x18\x02 \x01(\x05\x12\x18\n\x10unit_price_cents\x18\x03 \x01(\x03\"\xf1\x01\n\x08Shipment\x12\x13\n\x0bshipment_id\x18\x01 \x01(\t\x12#\n\x07\x63\x61rrier\x18\x02 \x01(\x0e\x32\x12.found.l11.Carrier\x12\'\n\x0b\x64\x65stination\x18\x03 \x01(\x0b\x32\x12.found.l11.Address\x12\"\n\x05items\x18\x04 \x03(\x0b\x32\x13.found.l11.LineItem\x12\x0c\n\x04tags\x18\x05 \x03(\t\x12\"\n\x15\x64\x65livered_unix_millis\x18\x06 \x01(\x03H\x00\x88\x01\x01\x42\x18\n\x16_delivered_unix_millisJ\x04\x08\x07\x10\x08R\x0ctracking_url\"N\n\x0cShipmentFile\x12\x16\n\x0eschema_version\x18\x01 \x01(\x05\x12&\n\tshipments\x18\x02 \x03(\x0b\x32\x13.found.l11.Shipment*Z\n\x07\x43\x61rrier\x12\x17\n\x13\x43\x41RRIER_UNSPECIFIED\x10\x00\x12\x0f\n\x0b\x43\x41RRIER_DHL\x10\x01\x12\x0f\n\x0b\x43\x41RRIER_UPS\x10\x02\x12\x14\n\x10\x43\x41RRIER_POSTNORD\x10\x03\x42\x37Z5dsapractice/api/Protobuf/Foundation/golang/pb/l11;l11b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'l11_capstone_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5dsapractice/api/Protobuf/Foundation/golang/pb/l11;l11'
  _globals['_CARRIER']._serialized_start=483
  _globals['_CARRIER']._serialized_end=573
  _globals['_ADDRESS']._serialized_start=33
  _globals['_ADDRESS']._serialized_end=93
  _globals['_LINEITEM']._serialized_start=95
  _globals['_LINEITEM']._serialized_end=157
  _globals['_SHIPMENT']._serialized_start=160
  _globals['_SHIPMENT']._serialized_end=401
  _globals['_SHIPMENTFILE']._serialized_start=403
  _globals['_SHIPMENTFILE']._serialized_end=481
# @@protoc_insertion_point(module_scope)
