// FOUNDATION LEVEL 12 - being a client: deadlines and retry-with-backoff.
// The server exists only to fail in a controlled, transient way.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: flaky.proto

package flakypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Flaky_Fetch_FullMethodName = "/foundation.flaky.v1.Flaky/Fetch"
	Flaky_Slow_FullMethodName  = "/foundation.flaky.v1.Flaky/Slow"
)

// FlakyClient is the client API for Flaky service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FlakyClient interface {
	Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error)
	Slow(ctx context.Context, in *SlowRequest, opts ...grpc.CallOption) (*SlowResponse, error)
}

type flakyClient struct {
	cc grpc.ClientConnInterface
}

func NewFlakyClient(cc grpc.ClientConnInterface) FlakyClient {
	return &flakyClient{cc}
}

func (c *flakyClient) Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchResponse)
	err := c.cc.Invoke(ctx, Flaky_Fetch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flakyClient) Slow(ctx context.Context, in *SlowRequest, opts ...grpc.CallOption) (*SlowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SlowResponse)
	err := c.cc.Invoke(ctx, Flaky_Slow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlakyServer is the server API for Flaky service.
// All implementations must embed UnimplementedFlakyServer
// for forward compatibility.
type FlakyServer interface {
	Fetch(context.Context, *FetchRequest) (*FetchResponse, error)
	Slow(context.Context, *SlowRequest) (*SlowResponse, error)
	mustEmbedUnimplementedFlakyServer()
}

// UnimplementedFlakyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFlakyServer struct{}

func (UnimplementedFlakyServer) Fetch(context.Context, *FetchRequest) (*FetchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedFlakyServer) Slow(context.Context, *SlowRequest) (*SlowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Slow not implemented")
}
func (UnimplementedFlakyServer) mustEmbedUnimplementedFlakyServer() {}
func (UnimplementedFlakyServer) testEmbeddedByValue()               {}

// UnsafeFlakyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlakyServer will
// result in compilation errors.
type UnsafeFlakyServer interface {
	mustEmbedUnimplementedFlakyServer()
}

func RegisterFlakyServer(s grpc.ServiceRegistrar, srv FlakyServer) {
	// If the following call panics, it indicates UnimplementedFlakyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Flaky_ServiceDesc, srv)
}

func _Flaky_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlakyServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Flaky_Fetch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlakyServer).Fetch(ctx, req.(*FetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flaky_Slow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlakyServer).Slow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Flaky_Slow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlakyServer).Slow(ctx, req.(*SlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Flaky_ServiceDesc is the grpc.ServiceDesc for Flaky service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Flaky_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "foundation.flaky.v1.Flaky",
	HandlerType: (*FlakyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Fetch",
			Handler:    _Flaky_Fetch_Handler,
		},
		{
			MethodName: "Slow",
			Handler:    _Flaky_Slow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flaky.proto",
}
