// FOUNDATION LEVEL 12 - being a client: deadlines and retry-with-backoff.
// The server exists only to fail in a controlled, transient way.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: flaky.proto

package flakypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_flaky_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flaky_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_flaky_proto_rawDescGZIP(), []int{0}
}

type FetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Attempt       int32                  `protobuf:"varint,2,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_flaky_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flaky_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_flaky_proto_rawDescGZIP(), []int{1}
}

func (x *FetchResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FetchResponse) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type SlowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlowRequest) Reset() {
	*x = SlowRequest{}
	mi := &file_flaky_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlowRequest) ProtoMessage() {}

func (x *SlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flaky_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlowRequest.ProtoReflect.Descriptor instead.
func (*SlowRequest) Descriptor() ([]byte, []int) {
	return file_flaky_proto_rawDescGZIP(), []int{2}
}

type SlowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlowResponse) Reset() {
	*x = SlowResponse{}
	mi := &file_flaky_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlowResponse) ProtoMessage() {}

func (x *SlowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flaky_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlowResponse.ProtoReflect.Descriptor instead.
func (*SlowResponse) Descriptor() ([]byte, []int) {
	return file_flaky_proto_rawDescGZIP(), []int{3}
}

func (x *SlowResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_flaky_proto protoreflect.FileDescriptor

const file_flaky_proto_rawDesc = "" +
	"\n" +
	"\vflaky.proto\x12\x13foundation.flaky.v1\"\x0e\n" +
	"\fFetchRequest\"A\n" +
	"\rFetchResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aattempt\x18\x02 \x01(\x05R\aattempt\"\r\n" +
	"\vSlowRequest\"&\n" +
	"\fSlowResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xa4\x01\n" +
	"\x05Flaky\x12N\n" +
	"\x05Fetch\x12!.foundation.flaky.v1.FetchRequest\x1a\".foundation.flaky.v1.FetchResponse\x12K\n" +
	"\x04Slow\x12 .foundation.flaky.v1.SlowRequest\x1a!.foundation.flaky.v1.SlowResponseB;Z9dsapractice/api/gRPC/Foundation/golang/pb/flakypb;flakypbb\x06proto3"

var (
	file_flaky_proto_rawDescOnce sync.Once
	file_flaky_proto_rawDescData []byte
)

func file_flaky_proto_rawDescGZIP() []byte {
	file_flaky_proto_rawDescOnce.Do(func() {
		file_flaky_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flaky_proto_rawDesc), len(file_flaky_proto_rawDesc)))
	})
	return file_flaky_proto_rawDescData
}

var file_flaky_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_flaky_proto_goTypes = []any{
	(*FetchRequest)(nil),  // 0: foundation.flaky.v1.FetchRequest
	(*FetchResponse)(nil), // 1: foundation.flaky.v1.FetchResponse
	(*SlowRequest)(nil),   // 2: foundation.flaky.v1.SlowRequest
	(*SlowResponse)(nil),  // 3: foundation.flaky.v1.SlowResponse
}
var file_flaky_proto_depIdxs = []int32{
	0, // 0: foundation.flaky.v1.Flaky.Fetch:input_type -> foundation.flaky.v1.FetchRequest
	2, // 1: foundation.flaky.v1.Flaky.Slow:input_type -> foundation.flaky.v1.SlowRequest
	1, // 2: foundation.flaky.v1.Flaky.Fetch:output_type -> foundation.flaky.v1.FetchResponse
	3, // 3: foundation.flaky.v1.Flaky.Slow:output_type -> foundation.flaky.v1.SlowResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_flaky_proto_init() }
func file_flaky_proto_init() {
	if File_flaky_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flaky_proto_rawDesc), len(file_flaky_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_flaky_proto_goTypes,
		DependencyIndexes: file_flaky_proto_depIdxs,
		MessageInfos:      file_flaky_proto_msgTypes,
	}.Build()
	File_flaky_proto = out.File
	file_flaky_proto_goTypes = nil
	file_flaky_proto_depIdxs = nil
}
