# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: demo.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'demo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndemo.proto\x12\x07\x64\x65mo.v1\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"4\n\x07\x41\x64\x64ress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\x0b\n\x03zip\x18\x03 \x01(\t\"\xb8\x03\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x1b\n\x04role\x18\x04 \x01(\x0e\x32\r.demo.v1.Role\x12\x0c\n\x04tags\x18\x05 \x03(\t\x12\'\n\x05\x61ttrs\x18\x06 \x03(\x0b\x32\x18.demo.v1.User.AttrsEntry\x12!\n\x07\x61\x64\x64ress\x18\x07 \x01(\x0b\x32\x10.demo.v1.Address\x12\x0f\n\x05phone\x18\x08 \x01(\tH\x00\x12\x0f\n\x05slack\x18\t \x01(\tH\x00\x12\x10\n\x03\x61ge\x18\n \x01(\x05H\x01\x88\x01\x01\x12.\n\ncreated_at\x18\x0b \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x15\n\rbalance_delta\x18\x0c \x01(\x11\x12\x14\n\x0clegacy_score\x18\r \x01(\x05\x12\x0e\n\x06\x61\x63tive\x18\x0e \x01(\x08\x12\x0e\n\x06rating\x18\x0f \x01(\x01\x12\x0e\n\x06\x61vatar\x18\x10 \x01(\x0c\x12\x0e\n\x06scores\x18\x11 \x03(\x05\x1a,\n\nAttrsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\t\n\x07\x63ontactB\x06\n\x04_age\"b\n\x05\x45vent\x12\n\n\x02id\x18\x01 \x01(\t\x12%\n\x07payload\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\x12&\n\x03ttl\x18\x03 \x01(\x0b\x32\x19.google.protobuf.Duration\"Y\n\tUserPatch\x12\x1b\n\x04user\x18\x01 \x01(\x0b\x32\r.demo.v1.User\x12/\n\x0bupdate_mask\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.FieldMask*;\n\x04Role\x12\x14\n\x10ROLE_UNSPECIFIED\x10\x00\x12\r\n\tROLE_USER\x10\x01\x12\x0e\n\nROLE_ADMIN\x10\x02\x42,Z*dsapractice/api/Protobuf/labs/golang/pb;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'demo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*dsapractice/api/Protobuf/labs/golang/pb;pb'
  _globals['_USER_ATTRSENTRY']._loaded_options = None
  _globals['_USER_ATTRSENTRY']._serialized_options = b'8\001'
  _globals['_ROLE']._serialized_start=837
  _globals['_ROLE']._serialized_end=896
  _globals['_ADDRESS']._serialized_start=149
  _globals['_ADDRESS']._serialized_end=201
  _globals['_USER']._serialized_start=204
  _globals['_USER']._serialized_end=644
  _globals['_USER_ATTRSENTRY']._serialized_start=581
  _globals['_USER_ATTRSENTRY']._serialized_end=625
  _globals['_EVENT']._serialized_start=646
  _globals['_EVENT']._serialized_end=744
  _globals['_USERPATCH']._serialized_start=746
  _globals['_USERPATCH']._serialized_end=835
# @@protoc_insertion_point(module_scope)
