// FOUNDATION LEVEL 12 - the bridge to gRPC.
//
// Note what is here: two ORDINARY messages, exactly like every level before
// this one, plus a `service` block. The service block is the only new thing
// gRPC adds to a .proto file, and it generates a SEPARATE file via a
// SEPARATE plugin (protoc-gen-go-grpc / grpcio-tools). The message codegen
// in this folder is produced without that plugin, so the service block below
// contributes exactly zero bytes to it - which is the point of the level.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: l12_bridge.proto

package l12

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_l12_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_l12_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_l12_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *EchoRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type EchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Length        int32                  `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_l12_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_l12_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_l12_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *EchoResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *EchoResponse) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

var File_l12_bridge_proto protoreflect.FileDescriptor

const file_l12_bridge_proto_rawDesc = "" +
	"\n" +
	"\x10l12_bridge.proto\x12\tfound.l12\"!\n" +
	"\vEchoRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\":\n" +
	"\fEchoResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x05R\x06length2F\n" +
	"\vEchoService\x127\n" +
	"\x04Echo\x12\x16.found.l12.EchoRequest\x1a\x17.found.l12.EchoResponseB7Z5dsapractice/api/Protobuf/Foundation/golang/pb/l12;l12b\x06proto3"

var (
	file_l12_bridge_proto_rawDescOnce sync.Once
	file_l12_bridge_proto_rawDescData []byte
)

func file_l12_bridge_proto_rawDescGZIP() []byte {
	file_l12_bridge_proto_rawDescOnce.Do(func() {
		file_l12_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_l12_bridge_proto_rawDesc), len(file_l12_bridge_proto_rawDesc)))
	})
	return file_l12_bridge_proto_rawDescData
}

var file_l12_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_l12_bridge_proto_goTypes = []any{
	(*EchoRequest)(nil),  // 0: found.l12.EchoRequest
	(*EchoResponse)(nil), // 1: found.l12.EchoResponse
}
var file_l12_bridge_proto_depIdxs = []int32{
	0, // 0: found.l12.EchoService.Echo:input_type -> found.l12.EchoRequest
	1, // 1: found.l12.EchoService.Echo:output_type -> found.l12.EchoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_l12_bridge_proto_init() }
func file_l12_bridge_proto_init() {
	if File_l12_bridge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_l12_bridge_proto_rawDesc), len(file_l12_bridge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_l12_bridge_proto_goTypes,
		DependencyIndexes: file_l12_bridge_proto_depIdxs,
		MessageInfos:      file_l12_bridge_proto_msgTypes,
	}.Build()
	File_l12_bridge_proto = out.File
	file_l12_bridge_proto_goTypes = nil
	file_l12_bridge_proto_depIdxs = nil
}
