//go:build ignore

// gen_popcount generates popcount_table_gen.go: a 256-entry lookup table of
// set-bit counts. The `ignore` build tag keeps this `package main` program out
// of the real package; it only ever runs via `go run gen_popcount.go`, which
// is what the //go:generate directive in the solution file does.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"math/bits"
	"os"
)

func main() {
	out := flag.String("o", "popcount_table_gen.go", "output file")
	flag.Parse()

	// go generate sets $GOPACKAGE to the package of the file containing the
	// directive; fall back for direct `go run` invocations.
	pkg := os.Getenv("GOPACKAGE")
	if pkg == "" {
		pkg = "directives"
	}

	var buf bytes.Buffer
	// This exact header shape ("Code generated ... DO NOT EDIT.") is a Go-wide
	// convention: gopls, linters and code review tools recognise it and treat
	// the file as generated.
	fmt.Fprintf(&buf, "// Code generated by gen_popcount.go; DO NOT EDIT.\n\npackage %s\n\n", pkg)
	buf.WriteString("// popcountTable[b] is the number of set bits in byte b.\n")
	buf.WriteString("var popcountTable = [256]uint8{\n")
	for i := range 256 {
		if i%16 == 0 {
			buf.WriteString("\t")
		}
		fmt.Fprintf(&buf, "%d,", bits.OnesCount8(uint8(i)))
		if i%16 == 15 {
			buf.WriteString("\n")
		} else {
			buf.WriteString(" ")
		}
	}
	buf.WriteString("}\n")

	src, err := format.Source(buf.Bytes()) // generated code should be gofmt-clean
	if err != nil {
		log.Fatalf("gen_popcount: format: %v", err)
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		log.Fatalf("gen_popcount: %v", err)
	}
}
