// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: demo.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enums: the first value MUST be 0 and is the default. Name it *_UNSPECIFIED.
type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	Role_ROLE_USER        Role = 1
	Role_ROLE_ADMIN       Role = 2
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_USER",
		2: "ROLE_ADMIN",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_USER":        1,
		"ROLE_ADMIN":       2,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_demo_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_demo_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_demo_proto_rawDescGZIP(), []int{0}
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Zip           string                 `protobuf:"bytes,3,opt,name=zip,proto3" json:"zip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_demo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_demo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_demo_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetZip() string {
	if x != nil {
		return x.Zip
	}
	return ""
}

type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field numbers 1-15 cost ONE byte of tag; 16+ cost two. Give them to the hot fields.
	Id      int64             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email   string            `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role    Role              `protobuf:"varint,4,opt,name=role,proto3,enum=demo.v1.Role" json:"role,omitempty"`
	Tags    []string          `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`                                                                             // packed automatically when scalar
	Attrs   map[string]string `protobuf:"bytes,6,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // sugar for repeated {key,value} entries
	Address *Address          `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`                                                                       // nested message: absent (nil) vs present-but-empty
	// Types that are valid to be assigned to Contact:
	//
	//	*User_Phone
	//	*User_Slack
	Contact       isUser_Contact         `protobuf_oneof:"contact"`
	Age           *int32                 `protobuf:"varint,10,opt,name=age,proto3,oneof" json:"age,omitempty"` // `optional` restores "was it set?" for scalars
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	BalanceDelta  int32                  `protobuf:"zigzag32,12,opt,name=balance_delta,json=balanceDelta,proto3" json:"balance_delta,omitempty"` // sint* uses ZigZag: small negatives stay small
	LegacyScore   int32                  `protobuf:"varint,13,opt,name=legacy_score,json=legacyScore,proto3" json:"legacy_score,omitempty"`      // int32 with a negative value costs 10 bytes!
	Active        bool                   `protobuf:"varint,14,opt,name=active,proto3" json:"active,omitempty"`
	Rating        float64                `protobuf:"fixed64,15,opt,name=rating,proto3" json:"rating,omitempty"`
	Avatar        []byte                 `protobuf:"bytes,16,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Scores        []int32                `protobuf:"varint,17,rep,packed,name=scores,proto3" json:"scores,omitempty"` // repeated scalars are PACKED: one tag + one length + all values
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_demo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_demo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_demo_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *User) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *User) GetAttrs() map[string]string {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *User) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *User) GetContact() isUser_Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

func (x *User) GetPhone() string {
	if x != nil {
		if x, ok := x.Contact.(*User_Phone); ok {
			return x.Phone
		}
	}
	return ""
}

func (x *User) GetSlack() string {
	if x != nil {
		if x, ok := x.Contact.(*User_Slack); ok {
			return x.Slack
		}
	}
	return ""
}

func (x *User) GetAge() int32 {
	if x != nil && x.Age != nil {
		return *x.Age
	}
	return 0
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetBalanceDelta() int32 {
	if x != nil {
		return x.BalanceDelta
	}
	return 0
}

func (x *User) GetLegacyScore() int32 {
	if x != nil {
		return x.LegacyScore
	}
	return 0
}

func (x *User) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *User) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *User) GetAvatar() []byte {
	if x != nil {
		return x.Avatar
	}
	return nil
}

func (x *User) GetScores() []int32 {
	if x != nil {
		return x.Scores
	}
	return nil
}

type isUser_Contact interface {
	isUser_Contact()
}

type User_Phone struct {
	Phone string `protobuf:"bytes,8,opt,name=phone,proto3,oneof"`
}

type User_Slack struct {
	Slack string `protobuf:"bytes,9,opt,name=slack,proto3,oneof"`
}

func (*User_Phone) isUser_Contact() {}

func (*User_Slack) isUser_Contact() {}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload       *anypb.Any             `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // any message, tagged with its type URL
	Ttl           *durationpb.Duration   `protobuf:"bytes,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_demo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_demo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_demo_proto_rawDescGZIP(), []int{2}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

type UserPatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"` // "only touch these fields"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPatch) Reset() {
	*x = UserPatch{}
	mi := &file_demo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPatch) ProtoMessage() {}

func (x *UserPatch) ProtoReflect() protoreflect.Message {
	mi := &file_demo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPatch.ProtoReflect.Descriptor instead.
func (*UserPatch) Descriptor() ([]byte, []int) {
	return file_demo_proto_rawDescGZIP(), []int{3}
}

func (x *UserPatch) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserPatch) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

var File_demo_proto protoreflect.FileDescriptor

const file_demo_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"demo.proto\x12\ademo.v1\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"G\n" +
	"\aAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x10\n" +
	"\x03zip\x18\x03 \x01(\tR\x03zip\"\xca\x04\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12!\n" +
	"\x04role\x18\x04 \x01(\x0e2\r.demo.v1.RoleR\x04role\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12.\n" +
	"\x05attrs\x18\x06 \x03(\v2\x18.demo.v1.User.AttrsEntryR\x05attrs\x12*\n" +
	"\aaddress\x18\a \x01(\v2\x10.demo.v1.AddressR\aaddress\x12\x16\n" +
	"\x05phone\x18\b \x01(\tH\x00R\x05phone\x12\x16\n" +
	"\x05slack\x18\t \x01(\tH\x00R\x05slack\x12\x15\n" +
	"\x03age\x18\n" +
	" \x01(\x05H\x01R\x03age\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12#\n" +
	"\rbalance_delta\x18\f \x01(\x11R\fbalanceDelta\x12!\n" +
	"\flegacy_score\x18\r \x01(\x05R\vlegacyScore\x12\x16\n" +
	"\x06active\x18\x0e \x01(\bR\x06active\x12\x16\n" +
	"\x06rating\x18\x0f \x01(\x01R\x06rating\x12\x16\n" +
	"\x06avatar\x18\x10 \x01(\fR\x06avatar\x12\x16\n" +
	"\x06scores\x18\x11 \x03(\x05R\x06scores\x1a8\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n" +
	"\acontactB\x06\n" +
	"\x04_age\"t\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\apayload\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\apayload\x12+\n" +
	"\x03ttl\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x03ttl\"k\n" +
	"\tUserPatch\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.demo.v1.UserR\x04user\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask*;\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tROLE_USER\x10\x01\x12\x0e\n" +
	"\n" +
	"ROLE_ADMIN\x10\x02B,Z*dsapractice/api/Protobuf/labs/golang/pb;pbb\x06proto3"

var (
	file_demo_proto_rawDescOnce sync.Once
	file_demo_proto_rawDescData []byte
)

func file_demo_proto_rawDescGZIP() []byte {
	file_demo_proto_rawDescOnce.Do(func() {
		file_demo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_demo_proto_rawDesc), len(file_demo_proto_rawDesc)))
	})
	return file_demo_proto_rawDescData
}

var file_demo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_demo_proto_goTypes = []any{
	(Role)(0),                     // 0: demo.v1.Role
	(*Address)(nil),               // 1: demo.v1.Address
	(*User)(nil),                  // 2: demo.v1.User
	(*Event)(nil),                 // 3: demo.v1.Event
	(*UserPatch)(nil),             // 4: demo.v1.UserPatch
	nil,                           // 5: demo.v1.User.AttrsEntry
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*anypb.Any)(nil),             // 7: google.protobuf.Any
	(*durationpb.Duration)(nil),   // 8: google.protobuf.Duration
	(*fieldmaskpb.FieldMask)(nil), // 9: google.protobuf.FieldMask
}
var file_demo_proto_depIdxs = []int32{
	0, // 0: demo.v1.User.role:type_name -> demo.v1.Role
	5, // 1: demo.v1.User.attrs:type_name -> demo.v1.User.AttrsEntry
	1, // 2: demo.v1.User.address:type_name -> demo.v1.Address
	6, // 3: demo.v1.User.created_at:type_name -> google.protobuf.Timestamp
	7, // 4: demo.v1.Event.payload:type_name -> google.protobuf.Any
	8, // 5: demo.v1.Event.ttl:type_name -> google.protobuf.Duration
	2, // 6: demo.v1.UserPatch.user:type_name -> demo.v1.User
	9, // 7: demo.v1.UserPatch.update_mask:type_name -> google.protobuf.FieldMask
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_demo_proto_init() }
func file_demo_proto_init() {
	if File_demo_proto != nil {
		return
	}
	file_demo_proto_msgTypes[1].OneofWrappers = []any{
		(*User_Phone)(nil),
		(*User_Slack)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_demo_proto_rawDesc), len(file_demo_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_demo_proto_goTypes,
		DependencyIndexes: file_demo_proto_depIdxs,
		EnumInfos:         file_demo_proto_enumTypes,
		MessageInfos:      file_demo_proto_msgTypes,
	}.Build()
	File_demo_proto = out.File
	file_demo_proto_goTypes = nil
	file_demo_proto_depIdxs = nil
}
