// FOUNDATION LEVEL 00 - the smallest useful .proto file there is.
//
// A .proto file is a SCHEMA: it describes the shape of some data once, in a
// language-neutral file, and then a compiler (protoc) turns it into real
// classes/structs for Python, Go, Java, Rust, ... This file is the whole
// contract for level 00.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: l00_ping.proto

package l00

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ping struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "= 1" is NOT a value and NOT an array index. It is this field's permanent
	// FIELD NUMBER - the only thing that identifies it on the wire. See level 01.
	Text          string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_l00_ping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_l00_ping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_l00_ping_proto_rawDescGZIP(), []int{0}
}

func (x *Ping) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_l00_ping_proto protoreflect.FileDescriptor

const file_l00_ping_proto_rawDesc = "" +
	"\n" +
	"\x0el00_ping.proto\x12\tfound.l00\"\x1a\n" +
	"\x04Ping\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04textB7Z5dsapractice/api/Protobuf/Foundation/golang/pb/l00;l00b\x06proto3"

var (
	file_l00_ping_proto_rawDescOnce sync.Once
	file_l00_ping_proto_rawDescData []byte
)

func file_l00_ping_proto_rawDescGZIP() []byte {
	file_l00_ping_proto_rawDescOnce.Do(func() {
		file_l00_ping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_l00_ping_proto_rawDesc), len(file_l00_ping_proto_rawDesc)))
	})
	return file_l00_ping_proto_rawDescData
}

var file_l00_ping_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_l00_ping_proto_goTypes = []any{
	(*Ping)(nil), // 0: found.l00.Ping
}
var file_l00_ping_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_l00_ping_proto_init() }
func file_l00_ping_proto_init() {
	if File_l00_ping_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_l00_ping_proto_rawDesc), len(file_l00_ping_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_l00_ping_proto_goTypes,
		DependencyIndexes: file_l00_ping_proto_depIdxs,
		MessageInfos:      file_l00_ping_proto_msgTypes,
	}.Build()
	File_l00_ping_proto = out.File
	file_l00_ping_proto_goTypes = nil
	file_l00_ping_proto_depIdxs = nil
}
