# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shop.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'shop.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nshop.proto\x12\x07shop.v1\"G\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0bprice_cents\x18\x03 \x01(\x03\x12\r\n\x05stock\x18\x04 \x01(\x05\"\x1f\n\x11GetProductRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"9\n\x13ListProductsRequest\x12\x13\n\x0bname_prefix\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\"%\n\x06Metric\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\"8\n\rUploadSummary\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12\x0b\n\x03sum\x18\x02 \x01(\x01\x12\x0b\n\x03\x61vg\x18\x03 \x01(\x01\")\n\x0b\x43hatMessage\x12\x0c\n\x04\x66rom\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t2\xfb\x01\n\x07\x43\x61talog\x12:\n\nGetProduct\x12\x1a.shop.v1.GetProductRequest\x1a\x10.shop.v1.Product\x12@\n\x0cListProducts\x12\x1c.shop.v1.ListProductsRequest\x1a\x10.shop.v1.Product0\x01\x12:\n\rUploadMetrics\x12\x0f.shop.v1.Metric\x1a\x16.shop.v1.UploadSummary(\x01\x12\x36\n\x04\x43hat\x12\x14.shop.v1.ChatMessage\x1a\x14.shop.v1.ChatMessage(\x01\x30\x01\x42\x30Z.dsapractice/api/gRPC/labs/golang/shoppb;shoppbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shop_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z.dsapractice/api/gRPC/labs/golang/shoppb;shoppb'
  _globals['_PRODUCT']._serialized_start=23
  _globals['_PRODUCT']._serialized_end=94
  _globals['_GETPRODUCTREQUEST']._serialized_start=96
  _globals['_GETPRODUCTREQUEST']._serialized_end=127
  _globals['_LISTPRODUCTSREQUEST']._serialized_start=129
  _globals['_LISTPRODUCTSREQUEST']._serialized_end=186
  _globals['_METRIC']._serialized_start=188
  _globals['_METRIC']._serialized_end=225
  _globals['_UPLOADSUMMARY']._serialized_start=227
  _globals['_UPLOADSUMMARY']._serialized_end=283
  _globals['_CHATMESSAGE']._serialized_start=285
  _globals['_CHATMESSAGE']._serialized_end=326
  _globals['_CATALOG']._serialized_start=329
  _globals['_CATALOG']._serialized_end=580
# @@protoc_insertion_point(module_scope)
