# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import shop_pb2 as shop__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in shop_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CatalogStub:
    """The four RPC shapes, all in one small service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProduct = channel.unary_unary(
                '/shop.v1.Catalog/GetProduct',
                request_serializer=shop__pb2.GetProductRequest.SerializeToString,
                response_deserializer=shop__pb2.Product.FromString,
                _registered_method=True)
        self.ListProducts = channel.unary_stream(
                '/shop.v1.Catalog/ListProducts',
                request_serializer=shop__pb2.ListProductsRequest.SerializeToString,
                response_deserializer=shop__pb2.Product.FromString,
                _registered_method=True)
        self.UploadMetrics = channel.stream_unary(
                '/shop.v1.Catalog/UploadMetrics',
                request_serializer=shop__pb2.Metric.SerializeToString,
                response_deserializer=shop__pb2.UploadSummary.FromString,
                _registered_method=True)
        self.Chat = channel.stream_stream(
                '/shop.v1.Catalog/Chat',
                request_serializer=shop__pb2.ChatMessage.SerializeToString,
                response_deserializer=shop__pb2.ChatMessage.FromString,
                _registered_method=True)


class CatalogServicer:
    """The four RPC shapes, all in one small service.
    """

    def GetProduct(self, request, context):
        """1. Unary: one request, one response (like a normal function call).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProducts(self, request, context):
        """2. Server streaming: one request, many responses.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadMetrics(self, request_iterator, context):
        """3. Client streaming: many requests, one response.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request_iterator, context):
        """4. Bidirectional streaming: both sides send whenever they like.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CatalogServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProduct,
                    request_deserializer=shop__pb2.GetProductRequest.FromString,
                    response_serializer=shop__pb2.Product.SerializeToString,
            ),
            'ListProducts': grpc.unary_stream_rpc_method_handler(
                    servicer.ListProducts,
                    request_deserializer=shop__pb2.ListProductsRequest.FromString,
                    response_serializer=shop__pb2.Product.SerializeToString,
            ),
            'UploadMetrics': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadMetrics,
                    request_deserializer=shop__pb2.Metric.FromString,
                    response_serializer=shop__pb2.UploadSummary.SerializeToString,
            ),
            'Chat': grpc.stream_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=shop__pb2.ChatMessage.FromString,
                    response_serializer=shop__pb2.ChatMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shop.v1.Catalog', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shop.v1.Catalog', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Catalog:
    """The four RPC shapes, all in one small service.
    """

    @staticmethod
    def GetProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shop.v1.Catalog/GetProduct',
            shop__pb2.GetProductRequest.SerializeToString,
            shop__pb2.Product.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/shop.v1.Catalog/ListProducts',
            shop__pb2.ListProductsRequest.SerializeToString,
            shop__pb2.Product.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadMetrics(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/shop.v1.Catalog/UploadMetrics',
            shop__pb2.Metric.SerializeToString,
            shop__pb2.UploadSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/shop.v1.Catalog/Chat',
            shop__pb2.ChatMessage.SerializeToString,
            shop__pb2.ChatMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
