"""
19 - Generic utilities - Reference Solution
==============================================

See `19_generic_utilities_explanation.py` for the full spec, rationale,
and acceptance criteria. Implements `Option[T]`, `Result[T, E]`, and the
bounded `clamp` utility exactly as specified there, using PEP 695 syntax
throughout.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from typing import Any, Protocol


# ---------------------------------------------------------------------------
# Option[T] - Some(value) | Nothing
# ---------------------------------------------------------------------------
@dataclass(frozen=True)
class Some[T]:
    """A present value. `__match_args__` (auto-generated by @dataclass)
    is what lets `case Some(value):` bind `value` positionally."""

    value: T


@dataclass(frozen=True)
class Nothing:
    """An absent value. No fields - every absence is interchangeable, so
    a single shared instance (`NOTHING` below) is all that's ever needed.
    """


# Nothing carries no data, so every "absent" value can share one instance
# instead of allocating a fresh Nothing() at every call site.
NOTHING: Nothing = Nothing()

type Option[T] = Some[T] | Nothing


def unwrap_or[T](opt: Option[T], default: T) -> T:
    """Return the wrapped value, or `default` if `opt` is `Nothing`."""
    match opt:
        case Some(value):
            return value
        case Nothing():
            return default


def map_option[T, U](opt: Option[T], fn: Callable[[T], U]) -> Option[U]:
    """Apply `fn` to the wrapped value if present; pass `Nothing` through."""
    match opt:
        case Some(value):
            return Some(fn(value))
        case Nothing():
            return NOTHING


def option_from_optional[T](value: T | None) -> Option[T]:
    """Bridge from ordinary `T | None` into `Option[T]`.

    This is the seam between idiomatic Python (which uses `None`
    pervasively - dict.get, re.match, ...) and Option-style code: convert
    at the boundary, then work with `Option[T]` from there on so "absent"
    and "the value None" can never be confused again.
    """
    return NOTHING if value is None else Some(value)


# ---------------------------------------------------------------------------
# Result[T, E] - Ok(value) | Err(error)
# ---------------------------------------------------------------------------
@dataclass(frozen=True)
class Ok[T, E]:
    """A successful outcome. `E` appears only in the type signature (Ok
    never holds an E value) - this is what lets `Result[T, E]` unify with
    `Err[T, E]` under one alias while each variant only stores one side.
    """

    value: T


@dataclass(frozen=True)
class Err[T, E]:
    """A failed outcome, carrying a typed error (not necessarily an
    Exception - could be a plain enum/string/dataclass describing what
    went wrong)."""

    error: E


type Result[T, E] = Ok[T, E] | Err[T, E]


def unwrap_or_result[T, E](result: Result[T, E], default: T) -> T:
    """Return the wrapped value, or `default` if `result` is `Err`."""
    match result:
        case Ok(value):
            return value
        case Err():
            return default


def map_result[T, U, E](result: Result[T, E], fn: Callable[[T], U]) -> Result[U, E]:
    """Apply `fn` to the wrapped value if `Ok`; pass `Err` through unchanged."""
    match result:
        case Ok(value):
            return Ok(fn(value))
        case Err(error):
            return Err(error)


def map_err[T, E, F](result: Result[T, E], fn: Callable[[E], F]) -> Result[T, F]:
    """Apply `fn` to the error if `Err`; pass `Ok` through unchanged."""
    match result:
        case Ok(value):
            return Ok(value)
        case Err(error):
            return Err(fn(error))


def result_from_exception[T](fn: Callable[[], T]) -> Result[T, Exception]:
    """Call `fn()`, converting a raised `Exception` into `Err`.

    Only `Exception` is caught, never `BaseException` - `KeyboardInterrupt`
    and `SystemExit` must always propagate; turning process-control
    signals into an ordinary `Err` value would make Ctrl-C silently
    swallowed by whatever called this.
    """
    try:
        return Ok(fn())
    except Exception as exc:  # noqa: BLE001 - intentional: this is the
        # documented bridge from exception-style code into Result-style
        # code; catching Exception (never BaseException) here is the
        # entire point of the function, not an accidental blind catch.
        return Err(exc)


# ---------------------------------------------------------------------------
# A standalone bounded generic utility.
# ---------------------------------------------------------------------------
class SupportsRichComparison(Protocol):
    """Structural bound: anything with `<`/`>` comparisons.

    Deliberately minimal (not stdlib's nonexistent "Comparable") - clamp
    only ever calls `<` and `>`, so the bound should only demand exactly
    that, no more.
    """

    def __lt__(self, other: Any) -> bool: ...
    def __gt__(self, other: Any) -> bool: ...


def clamp[T: SupportsRichComparison](value: T, lo: T, hi: T) -> T:
    """Constrain `value` to the closed range `[lo, hi]`.

    The bound `T: SupportsRichComparison` means mypy rejects `clamp(obj,
    lo, hi)` for any `T` that doesn't implement `__lt__`/`__gt__` - e.g.
    calling `clamp(some_dict, ...)` is a static type error, not a runtime
    `TypeError` discovered later. Contrast with `Option`/`Result` above,
    whose `T`/`E`/`U`/`F` are intentionally unbounded: those containers
    never compare their contents, only store and pass them through.
    """
    if value < lo:
        return lo
    if value > hi:
        return hi
    return value


# ---------------------------------------------------------------------------
# Best practices
# ---------------------------------------------------------------------------
# - Use `match`/`case` for dispatch over a discriminated union instead of
#   `isinstance` chains: it reads as "here are the cases," mirrors how
#   the type is documented (`Some[T] | Nothing`), and a trailing `case
#   _: assert_never(x)` gives a type checker an exhaustiveness hint that
#   an `if/elif` chain doesn't.
# - Keep every container variant `frozen=True` - Option/Result are value
#   types compared by structural equality (`Some(1) == Some(1)` is
#   `True` for free from the dataclass-generated `__eq__`), and freezing
#   them rules out the aliasing bugs a mutable `Some.value = ...` would
#   invite.
# - Only bound a type parameter (`T: SupportsRichComparison`) when the
#   function's body actually requires the bound's operations - an
#   unnecessarily narrow bound blocks legitimate callers for no benefit.
#
# Alternative approaches
# -----------------------
# - `enum.Enum` + a payload dict, or a single mutable class with an
#   `is_some: bool` flag and an `Optional` value field, would also encode
#   "present or absent" - both lose the type-level guarantee that you
#   can't accidentally read `.value` off an absent instance (with the
#   dataclass-union approach, `Nothing` simply has no `.value` attribute
#   at all - mypy catches the mistake statically).
# - The `returns` PyPI package (and similar) ships a fuller, more
#   feature-complete `Result`/`Maybe`/`IO` container ecosystem with
#   monadic combinators, do-notation-style syntax, and integration with
#   async code - reach for it in a real codebase once hand-rolled
#   `Result`/`Option` usage grows past a handful of call sites; this
#   exercise builds the minimal version to understand what such a
#   library is actually doing under the hood.
#
# WHEN GENERICS HURT IN PYTHON (the actual point of this exercise)
# --------------------------------------------------------------------
# - **No enforced exhaustiveness.** Rust's compiler refuses to compile a
#   `match` on an `enum` that doesn't cover every variant. Python's
#   `match` has no such enforcement at runtime - a missing `case`
#   silently falls through (or raises `NoneType has no attribute` two
#   functions downstream) unless you remember to add `case _:
#   assert_never(x)` and actually run mypy on every change. The
#   discipline is opt-in, not structural.
# - **Fighting the standard library.** `int()`, `dict[...]`, `open()`,
#   `json.loads()` - the entire stdlib raises exceptions, not `Result`s.
#   Wrapping every call to stdlib/third-party code in
#   `result_from_exception` just to keep a codebase "purely Result-based"
#   produces more boilerplate than it removes, and every unwrap
#   (`match result: case Ok(v): ... case Err(e): ...`) is strictly more
#   code than a `try`/`except` at the one call site that can actually
#   fail.
# - **Protocol/duck typing is the more idiomatic default.** Most of what
#   generics buy you in a statically-typed language (interchangeable
#   implementations behind one interface) is already free in Python via
#   structural typing (problem 18) - you don't need a generic `Repository
#   [T]` class hierarchy when a `Protocol` and normal duck typing already
#   let any object with the right shape work. Reach for PEP 695 generics
#   when you're building a genuinely reusable, type-parameterized
#   *container or algorithm* (this file, or e.g. a generic LRU cache) -
#   not as a default way to structure business logic.
# - **Verbosity at the call site.** `unwrap_or(opt, default)` is longer
#   and less familiar than `value or default` / `dict.get(key, default)`
#   for the common case Python already has idioms for; reserve
#   `Option`/`Result` for boundaries where the caller genuinely must be
#   forced to confront the failure/absence case, not as a blanket
#   replacement for `None`-checking everywhere.
