// inventory.proto — service contract for problem 24 (gRPC service).
//
// Generation command (run from the GoEngineering/ module root, with protoc,
// protoc-gen-go and protoc-gen-go-grpc on PATH — all three are pre-installed
// per the assignment brief):
//
//   protoc \
//     --proto_path=24_grpc_service/solution \
//     --go_out=. --go_opt=module=goengineering \
//     --go-grpc_out=. --go-grpc_opt=module=goengineering \
//     24_grpc_service/solution/inventory.proto
//
// This writes inventory.pb.go (message types) and inventory_grpc.pb.go
// (client/server stubs) to 24_grpc_service/solution/inventorypb/, driven by
// the go_package option below plus `module=goengineering` stripping the
// module prefix the same way problem 23's generation does.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: inventory.proto

package inventorypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Item is a single SKU's current stock record.
type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type GetItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemRequest) Reset() {
	*x = GetItemRequest{}
	mi := &file_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRequest) ProtoMessage() {}

func (x *GetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemRequest.ProtoReflect.Descriptor instead.
func (*GetItemRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *GetItemRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

type WatchStockRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Sku   string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	// Number of updates to emit before the server closes the stream on its
	// own; 0 means "until the client cancels or the deadline expires" (a real
	// service would stream indefinitely — this exists so tests can bound the
	// stream deterministically without relying on timing).
	MaxUpdates    int32 `protobuf:"varint,2,opt,name=max_updates,json=maxUpdates,proto3" json:"max_updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchStockRequest) Reset() {
	*x = WatchStockRequest{}
	mi := &file_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchStockRequest) ProtoMessage() {}

func (x *WatchStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchStockRequest.ProtoReflect.Descriptor instead.
func (*WatchStockRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *WatchStockRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *WatchStockRequest) GetMaxUpdates() int32 {
	if x != nil {
		return x.MaxUpdates
	}
	return 0
}

type StockUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnixTime      int64                  `protobuf:"varint,3,opt,name=unix_time,json=unixTime,proto3" json:"unix_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockUpdate) Reset() {
	*x = StockUpdate{}
	mi := &file_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockUpdate) ProtoMessage() {}

func (x *StockUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockUpdate.ProtoReflect.Descriptor instead.
func (*StockUpdate) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *StockUpdate) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *StockUpdate) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *StockUpdate) GetUnixTime() int64 {
	if x != nil {
		return x.UnixTime
	}
	return 0
}

type SaleRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaleRecord) Reset() {
	*x = SaleRecord{}
	mi := &file_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaleRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaleRecord) ProtoMessage() {}

func (x *SaleRecord) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaleRecord.ProtoReflect.Descriptor instead.
func (*SaleRecord) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *SaleRecord) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *SaleRecord) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type SalesSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalQuantity int64                  `protobuf:"varint,1,opt,name=total_quantity,json=totalQuantity,proto3" json:"total_quantity,omitempty"`
	RecordCount   int32                  `protobuf:"varint,2,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SalesSummary) Reset() {
	*x = SalesSummary{}
	mi := &file_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SalesSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SalesSummary) ProtoMessage() {}

func (x *SalesSummary) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SalesSummary.ProtoReflect.Descriptor instead.
func (*SalesSummary) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *SalesSummary) GetTotalQuantity() int64 {
	if x != nil {
		return x.TotalQuantity
	}
	return 0
}

func (x *SalesSummary) GetRecordCount() int32 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

var File_inventory_proto protoreflect.FileDescriptor

const file_inventory_proto_rawDesc = "" +
	"\n" +
	"\x0finventory.proto\x12\vinventorypb\"H\n" +
	"\x04Item\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\"\"\n" +
	"\x0eGetItemRequest\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\"F\n" +
	"\x11WatchStockRequest\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x1f\n" +
	"\vmax_updates\x18\x02 \x01(\x05R\n" +
	"maxUpdates\"X\n" +
	"\vStockUpdate\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity\x12\x1b\n" +
	"\tunix_time\x18\x03 \x01(\x03R\bunixTime\":\n" +
	"\n" +
	"SaleRecord\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity\"X\n" +
	"\fSalesSummary\x12%\n" +
	"\x0etotal_quantity\x18\x01 \x01(\x03R\rtotalQuantity\x12!\n" +
	"\frecord_count\x18\x02 \x01(\x05R\vrecordCount2\xdc\x01\n" +
	"\x10InventoryService\x129\n" +
	"\aGetItem\x12\x1b.inventorypb.GetItemRequest\x1a\x11.inventorypb.Item\x12H\n" +
	"\n" +
	"WatchStock\x12\x1e.inventorypb.WatchStockRequest\x1a\x18.inventorypb.StockUpdate0\x01\x12C\n" +
	"\vRecordSales\x12\x17.inventorypb.SaleRecord\x1a\x19.inventorypb.SalesSummary(\x01B4Z2goengineering/24_grpc_service/solution/inventorypbb\x06proto3"

var (
	file_inventory_proto_rawDescOnce sync.Once
	file_inventory_proto_rawDescData []byte
)

func file_inventory_proto_rawDescGZIP() []byte {
	file_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_proto_rawDesc), len(file_inventory_proto_rawDesc)))
	})
	return file_inventory_proto_rawDescData
}

var file_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_inventory_proto_goTypes = []any{
	(*Item)(nil),              // 0: inventorypb.Item
	(*GetItemRequest)(nil),    // 1: inventorypb.GetItemRequest
	(*WatchStockRequest)(nil), // 2: inventorypb.WatchStockRequest
	(*StockUpdate)(nil),       // 3: inventorypb.StockUpdate
	(*SaleRecord)(nil),        // 4: inventorypb.SaleRecord
	(*SalesSummary)(nil),      // 5: inventorypb.SalesSummary
}
var file_inventory_proto_depIdxs = []int32{
	1, // 0: inventorypb.InventoryService.GetItem:input_type -> inventorypb.GetItemRequest
	2, // 1: inventorypb.InventoryService.WatchStock:input_type -> inventorypb.WatchStockRequest
	4, // 2: inventorypb.InventoryService.RecordSales:input_type -> inventorypb.SaleRecord
	0, // 3: inventorypb.InventoryService.GetItem:output_type -> inventorypb.Item
	3, // 4: inventorypb.InventoryService.WatchStock:output_type -> inventorypb.StockUpdate
	5, // 5: inventorypb.InventoryService.RecordSales:output_type -> inventorypb.SalesSummary
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_inventory_proto_init() }
func file_inventory_proto_init() {
	if File_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_proto_rawDesc), len(file_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_proto_depIdxs,
		MessageInfos:      file_inventory_proto_msgTypes,
	}.Build()
	File_inventory_proto = out.File
	file_inventory_proto_goTypes = nil
	file_inventory_proto_depIdxs = nil
}
