// Code generated by reflectgen.GenerateStringer; DO NOT EDIT.

package reflectgen

import "strconv"

func (i Level) String() string {
	switch i {
	case LevelDebug:
		return "LevelDebug"
	case LevelInfo:
		return "LevelInfo"
	case LevelWarn:
		return "LevelWarn"
	case LevelError:
		return "LevelError"
	case LevelFatal:
		return "LevelFatal"
	default:
		return "Level(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
