// FOUNDATION LEVEL 04 - presence and default values.
//
// The two int32 fields below behave COMPLETELY differently even though they
// have the same type, because one of them is marked `optional`.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: l04_presence.proto

package l04

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Reading struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	SensorId string                 `protobuf:"bytes,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	// A plain proto3 scalar. It has NO presence: the encoder skips it whenever
	// it holds the type's default (0), so "never set" and "deliberately 0"
	// produce byte-for-byte identical output. You cannot recover the difference.
	Celsius int32 `protobuf:"varint,2,opt,name=celsius,proto3" json:"celsius,omitempty"`
	// The same type, but `optional` turns presence back on. Setting it to 0
	// now still emits the field on the wire, so a reader can ask "was this
	// sent?" and get a truthful answer.
	Humidity      *int32 `protobuf:"varint,3,opt,name=humidity,proto3,oneof" json:"humidity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reading) Reset() {
	*x = Reading{}
	mi := &file_l04_presence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reading) ProtoMessage() {}

func (x *Reading) ProtoReflect() protoreflect.Message {
	mi := &file_l04_presence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reading.ProtoReflect.Descriptor instead.
func (*Reading) Descriptor() ([]byte, []int) {
	return file_l04_presence_proto_rawDescGZIP(), []int{0}
}

func (x *Reading) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *Reading) GetCelsius() int32 {
	if x != nil {
		return x.Celsius
	}
	return 0
}

func (x *Reading) GetHumidity() int32 {
	if x != nil && x.Humidity != nil {
		return *x.Humidity
	}
	return 0
}

var File_l04_presence_proto protoreflect.FileDescriptor

const file_l04_presence_proto_rawDesc = "" +
	"\n" +
	"\x12l04_presence.proto\x12\tfound.l04\"n\n" +
	"\aReading\x12\x1b\n" +
	"\tsensor_id\x18\x01 \x01(\tR\bsensorId\x12\x18\n" +
	"\acelsius\x18\x02 \x01(\x05R\acelsius\x12\x1f\n" +
	"\bhumidity\x18\x03 \x01(\x05H\x00R\bhumidity\x88\x01\x01B\v\n" +
	"\t_humidityB7Z5dsapractice/api/Protobuf/Foundation/golang/pb/l04;l04b\x06proto3"

var (
	file_l04_presence_proto_rawDescOnce sync.Once
	file_l04_presence_proto_rawDescData []byte
)

func file_l04_presence_proto_rawDescGZIP() []byte {
	file_l04_presence_proto_rawDescOnce.Do(func() {
		file_l04_presence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_l04_presence_proto_rawDesc), len(file_l04_presence_proto_rawDesc)))
	})
	return file_l04_presence_proto_rawDescData
}

var file_l04_presence_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_l04_presence_proto_goTypes = []any{
	(*Reading)(nil), // 0: found.l04.Reading
}
var file_l04_presence_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_l04_presence_proto_init() }
func file_l04_presence_proto_init() {
	if File_l04_presence_proto != nil {
		return
	}
	file_l04_presence_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_l04_presence_proto_rawDesc), len(file_l04_presence_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_l04_presence_proto_goTypes,
		DependencyIndexes: file_l04_presence_proto_depIdxs,
		MessageInfos:      file_l04_presence_proto_msgTypes,
	}.Build()
	File_l04_presence_proto = out.File
	file_l04_presence_proto_goTypes = nil
	file_l04_presence_proto_depIdxs = nil
}
