// FOUNDATION LEVEL 07 - oneof: "exactly one of these, never two".

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: l07_oneof.proto

package l07

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Payment struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	AmountCents int64                  `protobuf:"varint,1,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	// The members of a oneof still have ordinary, unique field numbers - the
	// oneof is not a wire-format feature, it is a GENERATED-CODE feature. On
	// the wire only one of tags 2/3/4 is ever present; the generated setters
	// are what enforce that, by clearing the others for you.
	//
	// Types that are valid to be assigned to Method:
	//
	//	*Payment_CardToken
	//	*Payment_BankIban
	//	*Payment_WalletId
	Method        isPayment_Method `protobuf_oneof:"method"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_l07_oneof_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_l07_oneof_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_l07_oneof_proto_rawDescGZIP(), []int{0}
}

func (x *Payment) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *Payment) GetMethod() isPayment_Method {
	if x != nil {
		return x.Method
	}
	return nil
}

func (x *Payment) GetCardToken() string {
	if x != nil {
		if x, ok := x.Method.(*Payment_CardToken); ok {
			return x.CardToken
		}
	}
	return ""
}

func (x *Payment) GetBankIban() string {
	if x != nil {
		if x, ok := x.Method.(*Payment_BankIban); ok {
			return x.BankIban
		}
	}
	return ""
}

func (x *Payment) GetWalletId() string {
	if x != nil {
		if x, ok := x.Method.(*Payment_WalletId); ok {
			return x.WalletId
		}
	}
	return ""
}

type isPayment_Method interface {
	isPayment_Method()
}

type Payment_CardToken struct {
	CardToken string `protobuf:"bytes,2,opt,name=card_token,json=cardToken,proto3,oneof"`
}

type Payment_BankIban struct {
	BankIban string `protobuf:"bytes,3,opt,name=bank_iban,json=bankIban,proto3,oneof"`
}

type Payment_WalletId struct {
	WalletId string `protobuf:"bytes,4,opt,name=wallet_id,json=walletId,proto3,oneof"`
}

func (*Payment_CardToken) isPayment_Method() {}

func (*Payment_BankIban) isPayment_Method() {}

func (*Payment_WalletId) isPayment_Method() {}

var File_l07_oneof_proto protoreflect.FileDescriptor

const file_l07_oneof_proto_rawDesc = "" +
	"\n" +
	"\x0fl07_oneof.proto\x12\tfound.l07\"\x95\x01\n" +
	"\aPayment\x12!\n" +
	"\famount_cents\x18\x01 \x01(\x03R\vamountCents\x12\x1f\n" +
	"\n" +
	"card_token\x18\x02 \x01(\tH\x00R\tcardToken\x12\x1d\n" +
	"\tbank_iban\x18\x03 \x01(\tH\x00R\bbankIban\x12\x1d\n" +
	"\twallet_id\x18\x04 \x01(\tH\x00R\bwalletIdB\b\n" +
	"\x06methodB7Z5dsapractice/api/Protobuf/Foundation/golang/pb/l07;l07b\x06proto3"

var (
	file_l07_oneof_proto_rawDescOnce sync.Once
	file_l07_oneof_proto_rawDescData []byte
)

func file_l07_oneof_proto_rawDescGZIP() []byte {
	file_l07_oneof_proto_rawDescOnce.Do(func() {
		file_l07_oneof_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_l07_oneof_proto_rawDesc), len(file_l07_oneof_proto_rawDesc)))
	})
	return file_l07_oneof_proto_rawDescData
}

var file_l07_oneof_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_l07_oneof_proto_goTypes = []any{
	(*Payment)(nil), // 0: found.l07.Payment
}
var file_l07_oneof_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_l07_oneof_proto_init() }
func file_l07_oneof_proto_init() {
	if File_l07_oneof_proto != nil {
		return
	}
	file_l07_oneof_proto_msgTypes[0].OneofWrappers = []any{
		(*Payment_CardToken)(nil),
		(*Payment_BankIban)(nil),
		(*Payment_WalletId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_l07_oneof_proto_rawDesc), len(file_l07_oneof_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_l07_oneof_proto_goTypes,
		DependencyIndexes: file_l07_oneof_proto_depIdxs,
		MessageInfos:      file_l07_oneof_proto_msgTypes,
	}.Build()
	File_l07_oneof_proto = out.File
	file_l07_oneof_proto_goTypes = nil
	file_l07_oneof_proto_depIdxs = nil
}
