apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
# Secrets must be Base64 encoded in the YAML!
# echo -n "admin" | base64 -> YWRtaW4=
# echo -n "supersecretpassword123" | base64 -> c3VwZXJzZWNyZXRwYXNzd29yZDEyMw==
data:
  DB_USER: YWRtaW4=
  DB_PASS: c3VwZXJzZWNyZXRwYXNzd29yZDEyMw==
