// FOUNDATION LEVEL 03 - repeated fields: protobuf's lists/arrays.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: l03_repeated.proto

package l03

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Track struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Seconds       int32                  `protobuf:"varint,2,opt,name=seconds,proto3" json:"seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Track) Reset() {
	*x = Track{}
	mi := &file_l03_repeated_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Track) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Track) ProtoMessage() {}

func (x *Track) ProtoReflect() protoreflect.Message {
	mi := &file_l03_repeated_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Track.ProtoReflect.Descriptor instead.
func (*Track) Descriptor() ([]byte, []int) {
	return file_l03_repeated_proto_rawDescGZIP(), []int{0}
}

func (x *Track) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Track) GetSeconds() int32 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

type Playlist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`               // repeated STRING: one tag+length per element
	Ratings       []int32                `protobuf:"varint,3,rep,packed,name=ratings,proto3" json:"ratings,omitempty"` // repeated scalar NUMBER: packed into one run of bytes
	Tracks        []*Track               `protobuf:"bytes,4,rep,name=tracks,proto3" json:"tracks,omitempty"`           // repeated MESSAGE: never packed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Playlist) Reset() {
	*x = Playlist{}
	mi := &file_l03_repeated_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Playlist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Playlist) ProtoMessage() {}

func (x *Playlist) ProtoReflect() protoreflect.Message {
	mi := &file_l03_repeated_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Playlist.ProtoReflect.Descriptor instead.
func (*Playlist) Descriptor() ([]byte, []int) {
	return file_l03_repeated_proto_rawDescGZIP(), []int{1}
}

func (x *Playlist) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Playlist) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Playlist) GetRatings() []int32 {
	if x != nil {
		return x.Ratings
	}
	return nil
}

func (x *Playlist) GetTracks() []*Track {
	if x != nil {
		return x.Tracks
	}
	return nil
}

var File_l03_repeated_proto protoreflect.FileDescriptor

const file_l03_repeated_proto_rawDesc = "" +
	"\n" +
	"\x12l03_repeated.proto\x12\tfound.l03\"7\n" +
	"\x05Track\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\aseconds\x18\x02 \x01(\x05R\aseconds\"v\n" +
	"\bPlaylist\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x12\x18\n" +
	"\aratings\x18\x03 \x03(\x05R\aratings\x12(\n" +
	"\x06tracks\x18\x04 \x03(\v2\x10.found.l03.TrackR\x06tracksB7Z5dsapractice/api/Protobuf/Foundation/golang/pb/l03;l03b\x06proto3"

var (
	file_l03_repeated_proto_rawDescOnce sync.Once
	file_l03_repeated_proto_rawDescData []byte
)

func file_l03_repeated_proto_rawDescGZIP() []byte {
	file_l03_repeated_proto_rawDescOnce.Do(func() {
		file_l03_repeated_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_l03_repeated_proto_rawDesc), len(file_l03_repeated_proto_rawDesc)))
	})
	return file_l03_repeated_proto_rawDescData
}

var file_l03_repeated_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_l03_repeated_proto_goTypes = []any{
	(*Track)(nil),    // 0: found.l03.Track
	(*Playlist)(nil), // 1: found.l03.Playlist
}
var file_l03_repeated_proto_depIdxs = []int32{
	0, // 0: found.l03.Playlist.tracks:type_name -> found.l03.Track
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_l03_repeated_proto_init() }
func file_l03_repeated_proto_init() {
	if File_l03_repeated_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_l03_repeated_proto_rawDesc), len(file_l03_repeated_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_l03_repeated_proto_goTypes,
		DependencyIndexes: file_l03_repeated_proto_depIdxs,
		MessageInfos:      file_l03_repeated_proto_msgTypes,
	}.Build()
	File_l03_repeated_proto = out.File
	file_l03_repeated_proto_goTypes = nil
	file_l03_repeated_proto_depIdxs = nil
}
