// FOUNDATION LEVEL 03 - server streaming: one request, many responses.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: ticker.proto

package tickerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CountdownRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Named "start", not "from": "from" is a keyword in Python (and several other
	// target languages), and protoc does NOT rename fields for you. Picking
	// language-neutral field names is a real part of designing a .proto.
	Start         int32 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountdownRequest) Reset() {
	*x = CountdownRequest{}
	mi := &file_ticker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountdownRequest) ProtoMessage() {}

func (x *CountdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ticker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountdownRequest.ProtoReflect.Descriptor instead.
func (*CountdownRequest) Descriptor() ([]byte, []int) {
	return file_ticker_proto_rawDescGZIP(), []int{0}
}

func (x *CountdownRequest) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

type Tick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Last          bool                   `protobuf:"varint,2,opt,name=last,proto3" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tick) Reset() {
	*x = Tick{}
	mi := &file_ticker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tick) ProtoMessage() {}

func (x *Tick) ProtoReflect() protoreflect.Message {
	mi := &file_ticker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tick.ProtoReflect.Descriptor instead.
func (*Tick) Descriptor() ([]byte, []int) {
	return file_ticker_proto_rawDescGZIP(), []int{1}
}

func (x *Tick) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Tick) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

var File_ticker_proto protoreflect.FileDescriptor

const file_ticker_proto_rawDesc = "" +
	"\n" +
	"\fticker.proto\x12\x14foundation.ticker.v1\"(\n" +
	"\x10CountdownRequest\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x05R\x05start\"0\n" +
	"\x04Tick\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\x12\x12\n" +
	"\x04last\x18\x02 \x01(\bR\x04last2[\n" +
	"\x06Ticker\x12Q\n" +
	"\tCountdown\x12&.foundation.ticker.v1.CountdownRequest\x1a\x1a.foundation.ticker.v1.Tick0\x01B=Z;dsapractice/api/gRPC/Foundation/golang/pb/tickerpb;tickerpbb\x06proto3"

var (
	file_ticker_proto_rawDescOnce sync.Once
	file_ticker_proto_rawDescData []byte
)

func file_ticker_proto_rawDescGZIP() []byte {
	file_ticker_proto_rawDescOnce.Do(func() {
		file_ticker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ticker_proto_rawDesc), len(file_ticker_proto_rawDesc)))
	})
	return file_ticker_proto_rawDescData
}

var file_ticker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ticker_proto_goTypes = []any{
	(*CountdownRequest)(nil), // 0: foundation.ticker.v1.CountdownRequest
	(*Tick)(nil),             // 1: foundation.ticker.v1.Tick
}
var file_ticker_proto_depIdxs = []int32{
	0, // 0: foundation.ticker.v1.Ticker.Countdown:input_type -> foundation.ticker.v1.CountdownRequest
	1, // 1: foundation.ticker.v1.Ticker.Countdown:output_type -> foundation.ticker.v1.Tick
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ticker_proto_init() }
func file_ticker_proto_init() {
	if File_ticker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ticker_proto_rawDesc), len(file_ticker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ticker_proto_goTypes,
		DependencyIndexes: file_ticker_proto_depIdxs,
		MessageInfos:      file_ticker_proto_msgTypes,
	}.Build()
	File_ticker_proto = out.File
	file_ticker_proto_goTypes = nil
	file_ticker_proto_depIdxs = nil
}
