// FOUNDATION LEVEL 03 - server streaming: one request, many responses.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: ticker.proto

package tickerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Ticker_Countdown_FullMethodName = "/foundation.ticker.v1.Ticker/Countdown"
)

// TickerClient is the client API for Ticker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TickerClient interface {
	// The "stream" keyword on the RETURN type is the entire difference between
	// a unary RPC and a server-streaming one.
	Countdown(ctx context.Context, in *CountdownRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Tick], error)
}

type tickerClient struct {
	cc grpc.ClientConnInterface
}

func NewTickerClient(cc grpc.ClientConnInterface) TickerClient {
	return &tickerClient{cc}
}

func (c *tickerClient) Countdown(ctx context.Context, in *CountdownRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Tick], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Ticker_ServiceDesc.Streams[0], Ticker_Countdown_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CountdownRequest, Tick]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ticker_CountdownClient = grpc.ServerStreamingClient[Tick]

// TickerServer is the server API for Ticker service.
// All implementations must embed UnimplementedTickerServer
// for forward compatibility.
type TickerServer interface {
	// The "stream" keyword on the RETURN type is the entire difference between
	// a unary RPC and a server-streaming one.
	Countdown(*CountdownRequest, grpc.ServerStreamingServer[Tick]) error
	mustEmbedUnimplementedTickerServer()
}

// UnimplementedTickerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTickerServer struct{}

func (UnimplementedTickerServer) Countdown(*CountdownRequest, grpc.ServerStreamingServer[Tick]) error {
	return status.Error(codes.Unimplemented, "method Countdown not implemented")
}
func (UnimplementedTickerServer) mustEmbedUnimplementedTickerServer() {}
func (UnimplementedTickerServer) testEmbeddedByValue()                {}

// UnsafeTickerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TickerServer will
// result in compilation errors.
type UnsafeTickerServer interface {
	mustEmbedUnimplementedTickerServer()
}

func RegisterTickerServer(s grpc.ServiceRegistrar, srv TickerServer) {
	// If the following call panics, it indicates UnimplementedTickerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Ticker_ServiceDesc, srv)
}

func _Ticker_Countdown_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CountdownRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TickerServer).Countdown(m, &grpc.GenericServerStream[CountdownRequest, Tick]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ticker_CountdownServer = grpc.ServerStreamingServer[Tick]

// Ticker_ServiceDesc is the grpc.ServiceDesc for Ticker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ticker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "foundation.ticker.v1.Ticker",
	HandlerType: (*TickerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Countdown",
			Handler:       _Ticker_Countdown_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ticker.proto",
}
