# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: l03_repeated.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'l03_repeated.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12l03_repeated.proto\x12\tfound.l03\"\'\n\x05Track\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07seconds\x18\x02 \x01(\x05\"Y\n\x08Playlist\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04tags\x18\x02 \x03(\t\x12\x0f\n\x07ratings\x18\x03 \x03(\x05\x12 \n\x06tracks\x18\x04 \x03(\x0b\x32\x10.found.l03.TrackB7Z5dsapractice/api/Protobuf/Foundation/golang/pb/l03;l03b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'l03_repeated_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5dsapractice/api/Protobuf/Foundation/golang/pb/l03;l03'
  _globals['_TRACK']._serialized_start=33
  _globals['_TRACK']._serialized_end=72
  _globals['_PLAYLIST']._serialized_start=74
  _globals['_PLAYLIST']._serialized_end=163
# @@protoc_insertion_point(module_scope)
