# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: l09_batch.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'l09_batch.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fl09_batch.proto\x12\tfound.l09\",\n\x06Sample\x12\x13\n\x0bunix_millis\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\x01\"D\n\x0bSensorBatch\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\"\n\x07samples\x18\x02 \x03(\x0b\x32\x11.found.l09.SampleB7Z5dsapractice/api/Protobuf/Foundation/golang/pb/l09;l09b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'l09_batch_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5dsapractice/api/Protobuf/Foundation/golang/pb/l09;l09'
  _globals['_SAMPLE']._serialized_start=30
  _globals['_SAMPLE']._serialized_end=74
  _globals['_SENSORBATCH']._serialized_start=76
  _globals['_SENSORBATCH']._serialized_end=144
# @@protoc_insertion_point(module_scope)
