# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: l12_bridge.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'l12_bridge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10l12_bridge.proto\x12\tfound.l12\"\x1b\n\x0b\x45\x63hoRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\",\n\x0c\x45\x63hoResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0e\n\x06length\x18\x02 \x01(\x05\x32\x46\n\x0b\x45\x63hoService\x12\x37\n\x04\x45\x63ho\x12\x16.found.l12.EchoRequest\x1a\x17.found.l12.EchoResponseB7Z5dsapractice/api/Protobuf/Foundation/golang/pb/l12;l12b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'l12_bridge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5dsapractice/api/Protobuf/Foundation/golang/pb/l12;l12'
  _globals['_ECHOREQUEST']._serialized_start=31
  _globals['_ECHOREQUEST']._serialized_end=58
  _globals['_ECHORESPONSE']._serialized_start=60
  _globals['_ECHORESPONSE']._serialized_end=104
  _globals['_ECHOSERVICE']._serialized_start=106
  _globals['_ECHOSERVICE']._serialized_end=176
# @@protoc_insertion_point(module_scope)
