# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: authz.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'authz.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61uthz.proto\x12\x13\x66oundation.authz.v1\"\x14\n\x12ListReportsRequest\"%\n\x13ListReportsResponse\x12\x0e\n\x06titles\x18\x01 \x03(\t\"!\n\x13\x44\x65leteReportRequest\x12\n\n\x02id\x18\x01 \x01(\x05\")\n\x14\x44\x65leteReportResponse\x12\x11\n\tremaining\x18\x01 \x01(\x05\x32\xd0\x01\n\x07Reports\x12`\n\x0bListReports\x12\'.foundation.authz.v1.ListReportsRequest\x1a(.foundation.authz.v1.ListReportsResponse\x12\x63\n\x0c\x44\x65leteReport\x12(.foundation.authz.v1.DeleteReportRequest\x1a).foundation.authz.v1.DeleteReportResponseB;Z9dsapractice/api/gRPC/Foundation/golang/pb/authzpb;authzpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'authz_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9dsapractice/api/gRPC/Foundation/golang/pb/authzpb;authzpb'
  _globals['_LISTREPORTSREQUEST']._serialized_start=36
  _globals['_LISTREPORTSREQUEST']._serialized_end=56
  _globals['_LISTREPORTSRESPONSE']._serialized_start=58
  _globals['_LISTREPORTSRESPONSE']._serialized_end=95
  _globals['_DELETEREPORTREQUEST']._serialized_start=97
  _globals['_DELETEREPORTREQUEST']._serialized_end=130
  _globals['_DELETEREPORTRESPONSE']._serialized_start=132
  _globals['_DELETEREPORTRESPONSE']._serialized_end=173
  _globals['_REPORTS']._serialized_start=176
  _globals['_REPORTS']._serialized_end=384
# @@protoc_insertion_point(module_scope)
