# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import flaky_pb2 as flaky__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in flaky_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FlakyStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Fetch = channel.unary_unary(
                '/foundation.flaky.v1.Flaky/Fetch',
                request_serializer=flaky__pb2.FetchRequest.SerializeToString,
                response_deserializer=flaky__pb2.FetchResponse.FromString,
                _registered_method=True)
        self.Slow = channel.unary_unary(
                '/foundation.flaky.v1.Flaky/Slow',
                request_serializer=flaky__pb2.SlowRequest.SerializeToString,
                response_deserializer=flaky__pb2.SlowResponse.FromString,
                _registered_method=True)


class FlakyServicer:
    """Missing associated documentation comment in .proto file."""

    def Fetch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Slow(self, request, context):
        """always takes longer than the deadline
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlakyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Fetch': grpc.unary_unary_rpc_method_handler(
                    servicer.Fetch,
                    request_deserializer=flaky__pb2.FetchRequest.FromString,
                    response_serializer=flaky__pb2.FetchResponse.SerializeToString,
            ),
            'Slow': grpc.unary_unary_rpc_method_handler(
                    servicer.Slow,
                    request_deserializer=flaky__pb2.SlowRequest.FromString,
                    response_serializer=flaky__pb2.SlowResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'foundation.flaky.v1.Flaky', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('foundation.flaky.v1.Flaky', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Flaky:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Fetch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/foundation.flaky.v1.Flaky/Fetch',
            flaky__pb2.FetchRequest.SerializeToString,
            flaky__pb2.FetchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Slow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/foundation.flaky.v1.Flaky/Slow',
            flaky__pb2.SlowRequest.SerializeToString,
            flaky__pb2.SlowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
