# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metaecho.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'metaecho.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emetaecho.proto\x12\x16\x66oundation.metaecho.v1\"\x1b\n\x0b\x45\x63hoRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"4\n\x0c\x45\x63hoResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x16\n\x0esaw_request_id\x18\x02 \x01(\t2]\n\x08MetaEcho\x12Q\n\x04\x45\x63ho\x12#.foundation.metaecho.v1.EchoRequest\x1a$.foundation.metaecho.v1.EchoResponseBAZ?dsapractice/api/gRPC/Foundation/golang/pb/metaechopb;metaechopbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metaecho_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z?dsapractice/api/gRPC/Foundation/golang/pb/metaechopb;metaechopb'
  _globals['_ECHOREQUEST']._serialized_start=42
  _globals['_ECHOREQUEST']._serialized_end=69
  _globals['_ECHORESPONSE']._serialized_start=71
  _globals['_ECHORESPONSE']._serialized_end=123
  _globals['_METAECHO']._serialized_start=125
  _globals['_METAECHO']._serialized_end=218
# @@protoc_insertion_point(module_scope)
