# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import notes_pb2 as notes__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in notes_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NotesStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNote = channel.unary_unary(
                '/foundation.notes.v1.Notes/GetNote',
                request_serializer=notes__pb2.GetNoteRequest.SerializeToString,
                response_deserializer=notes__pb2.Note.FromString,
                _registered_method=True)
        self.CreateNote = channel.unary_unary(
                '/foundation.notes.v1.Notes/CreateNote',
                request_serializer=notes__pb2.CreateNoteRequest.SerializeToString,
                response_deserializer=notes__pb2.Note.FromString,
                _registered_method=True)
        self.DeleteNote = channel.unary_unary(
                '/foundation.notes.v1.Notes/DeleteNote',
                request_serializer=notes__pb2.DeleteNoteRequest.SerializeToString,
                response_deserializer=notes__pb2.DeleteNoteResponse.FromString,
                _registered_method=True)


class NotesServicer:
    """Missing associated documentation comment in .proto file."""

    def GetNote(self, request, context):
        """public: no credential needed
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateNote(self, request, context):
        """any authenticated caller
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteNote(self, request, context):
        """admin role only
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNote': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNote,
                    request_deserializer=notes__pb2.GetNoteRequest.FromString,
                    response_serializer=notes__pb2.Note.SerializeToString,
            ),
            'CreateNote': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNote,
                    request_deserializer=notes__pb2.CreateNoteRequest.FromString,
                    response_serializer=notes__pb2.Note.SerializeToString,
            ),
            'DeleteNote': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteNote,
                    request_deserializer=notes__pb2.DeleteNoteRequest.FromString,
                    response_serializer=notes__pb2.DeleteNoteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'foundation.notes.v1.Notes', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('foundation.notes.v1.Notes', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Notes:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetNote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/foundation.notes.v1.Notes/GetNote',
            notes__pb2.GetNoteRequest.SerializeToString,
            notes__pb2.Note.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateNote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/foundation.notes.v1.Notes/CreateNote',
            notes__pb2.CreateNoteRequest.SerializeToString,
            notes__pb2.Note.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteNote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/foundation.notes.v1.Notes/DeleteNote',
            notes__pb2.DeleteNoteRequest.SerializeToString,
            notes__pb2.DeleteNoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
