package reflectgen

// Level is a log level enum. Its String method lives in level_string_gen.go,
// generated by GenerateStringer from THIS file — see
// TestGeneratedLevelStringIsFresh for the regenerate-and-diff check.
type Level int

const (
	LevelDebug Level = iota - 1 // -1: iota arithmetic must be evaluated, not guessed
	LevelInfo                   // 0
	LevelWarn                   // 1
	LevelError                  // 2
	_                           // 3 is reserved: blank names are skipped
	LevelFatal                  // 4
)

// LevelDefault is an alias of an existing value; the generator must not emit
// a duplicate switch case for it.
const LevelDefault = LevelInfo
