# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cache_pb2 as cache__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cache_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SemanticCacheServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckCache = channel.unary_unary(
                '/semanticcache.SemanticCacheService/CheckCache',
                request_serializer=cache__pb2.CacheRequest.SerializeToString,
                response_deserializer=cache__pb2.CacheResponse.FromString,
                _registered_method=True)
        self.SetCache = channel.unary_unary(
                '/semanticcache.SemanticCacheService/SetCache',
                request_serializer=cache__pb2.SetCacheRequest.SerializeToString,
                response_deserializer=cache__pb2.SetCacheResponse.FromString,
                _registered_method=True)


class SemanticCacheServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CheckCache(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCache(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SemanticCacheServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckCache': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckCache,
                    request_deserializer=cache__pb2.CacheRequest.FromString,
                    response_serializer=cache__pb2.CacheResponse.SerializeToString,
            ),
            'SetCache': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCache,
                    request_deserializer=cache__pb2.SetCacheRequest.FromString,
                    response_serializer=cache__pb2.SetCacheResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'semanticcache.SemanticCacheService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('semanticcache.SemanticCacheService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SemanticCacheService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semanticcache.SemanticCacheService/CheckCache',
            cache__pb2.CacheRequest.SerializeToString,
            cache__pb2.CacheResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semanticcache.SemanticCacheService/SetCache',
            cache__pb2.SetCacheRequest.SerializeToString,
            cache__pb2.SetCacheResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
