// FOUNDATION LEVEL 09 - the schema for a tiny two-program pipeline:
// one program writes a file of these, another program reads it back.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: l09_batch.proto

package l09

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnixMillis    int64                  `protobuf:"varint,1,opt,name=unix_millis,json=unixMillis,proto3" json:"unix_millis,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sample) Reset() {
	*x = Sample{}
	mi := &file_l09_batch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sample) ProtoMessage() {}

func (x *Sample) ProtoReflect() protoreflect.Message {
	mi := &file_l09_batch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sample.ProtoReflect.Descriptor instead.
func (*Sample) Descriptor() ([]byte, []int) {
	return file_l09_batch_proto_rawDescGZIP(), []int{0}
}

func (x *Sample) GetUnixMillis() int64 {
	if x != nil {
		return x.UnixMillis
	}
	return 0
}

func (x *Sample) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SensorBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Samples       []*Sample              `protobuf:"bytes,2,rep,name=samples,proto3" json:"samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorBatch) Reset() {
	*x = SensorBatch{}
	mi := &file_l09_batch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorBatch) ProtoMessage() {}

func (x *SensorBatch) ProtoReflect() protoreflect.Message {
	mi := &file_l09_batch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorBatch.ProtoReflect.Descriptor instead.
func (*SensorBatch) Descriptor() ([]byte, []int) {
	return file_l09_batch_proto_rawDescGZIP(), []int{1}
}

func (x *SensorBatch) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SensorBatch) GetSamples() []*Sample {
	if x != nil {
		return x.Samples
	}
	return nil
}

var File_l09_batch_proto protoreflect.FileDescriptor

const file_l09_batch_proto_rawDesc = "" +
	"\n" +
	"\x0fl09_batch.proto\x12\tfound.l09\"?\n" +
	"\x06Sample\x12\x1f\n" +
	"\vunix_millis\x18\x01 \x01(\x03R\n" +
	"unixMillis\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"W\n" +
	"\vSensorBatch\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12+\n" +
	"\asamples\x18\x02 \x03(\v2\x11.found.l09.SampleR\asamplesB7Z5dsapractice/api/Protobuf/Foundation/golang/pb/l09;l09b\x06proto3"

var (
	file_l09_batch_proto_rawDescOnce sync.Once
	file_l09_batch_proto_rawDescData []byte
)

func file_l09_batch_proto_rawDescGZIP() []byte {
	file_l09_batch_proto_rawDescOnce.Do(func() {
		file_l09_batch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_l09_batch_proto_rawDesc), len(file_l09_batch_proto_rawDesc)))
	})
	return file_l09_batch_proto_rawDescData
}

var file_l09_batch_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_l09_batch_proto_goTypes = []any{
	(*Sample)(nil),      // 0: found.l09.Sample
	(*SensorBatch)(nil), // 1: found.l09.SensorBatch
}
var file_l09_batch_proto_depIdxs = []int32{
	0, // 0: found.l09.SensorBatch.samples:type_name -> found.l09.Sample
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_l09_batch_proto_init() }
func file_l09_batch_proto_init() {
	if File_l09_batch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_l09_batch_proto_rawDesc), len(file_l09_batch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_l09_batch_proto_goTypes,
		DependencyIndexes: file_l09_batch_proto_depIdxs,
		MessageInfos:      file_l09_batch_proto_msgTypes,
	}.Build()
	File_l09_batch_proto = out.File
	file_l09_batch_proto_goTypes = nil
	file_l09_batch_proto_depIdxs = nil
}
