// REAL-WORLD EXAMPLE: hooklift/gowsdl (External 1)
// Demonstrates: Code generation from WSDL and strongly typed method calls.
// Note: You would normally run `gowsdl http://www.dataaccess.com/webservicesserver/numberconversion.wso?WSDL` first.
package main

import (
	"fmt"
	// "myservice/generated" // This package would be generated by gowsdl
)

func main() {
	// 1. Initialize the generated client
	// client := generated.NewNumberConversionSoapType("", true, nil)
	
	// 2. Call the strongly-typed method
	// req := &generated.NumberToWords{UbiNum: 500}
	// resp, err := client.NumberToWords(req)
	// if err != nil {
	// 	panic(err)
	// }
	
	// fmt.Println(resp.NumberToWordsResult)
	fmt.Println("Gowsdl relies on generated code. See comments for usage.")
}
