"""
================================================================================
SOLUTION · LeetCode 27 · Remove Element                                  [Easy]
https://leetcode.com/problems/remove-element/
================================================================================

THE CORE IDEA
-------------
LC 26 with the predicate swapped out. That is the first half of the answer:

    w = 0
    for x in nums:
        if KEEP(x):            # LC 26: x != nums[w-1]    LC 27: x != val
            nums[w] = x
            w += 1
    return w

The second half is a sentence in the statement that LC 26 did not have:

    "The order of the elements MAY BE CHANGED."

That sentence is not decoration — it is permission to use a different
algorithm. If order must be preserved you have to SHIFT survivors leftward,
which touches every survivor. If order is free, you can instead FILL THE HOLE
FROM THE BACK and touch only the removals:

    l, n = 0, len(nums)
    while l < n:
        if nums[l] == val:
            nums[l] = nums[n - 1]      # drop the last element into the hole
            n -= 1                     # the array is now one shorter
        else:                          # do NOT advance l — the value you just
            l += 1                     # pulled in has never been examined
    return n

    writes = exactly count(val)         vs      writes = number of SURVIVORS

Two algorithms, both O(n) time and O(1) space, with opposite cost profiles.
Which one wins depends on the data, and knowing that is the point of the
problem. The measured crossover is at 50% density, which is not a coincidence —
it is the density at which count(val) == n - count(val).

    nums = [0,1,2,2,3,0,4,2]   val = 2

    order-preserving:   [0,1,3,0,4 | 2,4,2]   k=5, 5 writes
    fill-from-back:     [0,1,4,0,3 | 0,4,2]   k=5, 3 writes

Look at that second prefix: `[0,1,4,0,3]`. It is character-for-character the
output LeetCode prints in its own Example 2. Their example was generated by the
fill-from-back algorithm — which is a fair hint about which answer they had in
mind, and a good thing to notice out loud.

THE PATTERN. Fill-from-back is a PARTITION: when you use the swap form instead
of the overwrite form, the array ends up split into "keepers | removed" with a
single index separating them. That is the primitive inside quicksort, LC 905
(Sort Array by Parity) and LC 75 (Sort Colors). Recognise it and three more
problems come free.


================================================================================
APPROACH 0 · Rebuild the list (say it, price it, do not submit it)
================================================================================
    keep = [x for x in nums if x != val]
    nums[:len(keep)] = keep
    return len(keep)

Correct, and — surprise — it is the FASTEST option in CPython, about 2x
quicker than either hand-written two-pointer loop at every density measured,
because the whole loop runs in C instead of in the interpreter. See the
benchmark at the bottom; the numbers come from running this very file.

It is still the wrong submission, for one reason: O(n) extra space. The problem
exists to test in-place compaction. Saying "the one-liner is `[x for x in nums
if x != val]`, and in CPython it will actually beat my two-pointer loop, but it
allocates a second array so it misses the point of the exercise" is a strictly
better answer than pretending the one-liner does not exist.

What you must NOT do:

    while val in nums:              # ✗ O(n^2)
        nums.remove(val)

`in` scans, `.remove()` scans again and then shifts the entire tail left. One
full pass per removal. Measured at 50% density: ~66x slower at n=2000, ~135x
at n=4000, ~252x at n=8000. The absolute figures move a little between runs;
the fact that the RATIO doubles when n doubles does not, and that doubling is
the signature of a quadratic. The benchmark at the bottom prints this live.


================================================================================
APPROACH 1 · Order-preserving read/write pointers ✅
================================================================================

    w = 0
    for x in nums:                  # iterate VALUES, not indices
        if x != val:
            nums[w] = x
            w += 1
    return w

    Time O(n) · Space O(1) · MUTATES the input · writes = #survivors

Same invariant as LC 26: `w <= r` always, so every cell you overwrite has
already been read. That is what makes writing into the array you are reading
safe without a buffer.

⚠️  WHY `for x in nums` AND NOT `for r in range(len(nums))`
    Iterating the list directly is safe here even though the loop body writes
    to it, because the writes only ever land at index w <= r, i.e. strictly
    behind the iterator. Cells ahead of the cursor are never touched, so the
    iterator can never see a value that was not in the original array.

    It is also faster — measured 0.405 ms vs 0.527 ms at n=20000 — because it
    drops one `BINARY_SUBSCR` per element. This is the opposite of the usual
    advice ("never mutate what you iterate"), and the reason the usual advice
    does not apply is worth being able to state precisely.

    Do NOT extend this to a loop that inserts or deletes. Overwriting a slot
    behind the cursor is fine; changing the LENGTH is what breaks iterators.

⚠️  START AT w = 0, NOT w = 1
    Here `w = 0` is correct — the exact opposite of LC 26. In LC 26 the first
    element is unique by definition and stays put. Here the first element might
    BE `val`, so nothing is guaranteed and there is no head to skip. Two
    problems with the same skeleton and opposite initialisation; that asymmetry
    is precisely the thing that trips people who memorised the shape without
    the reason.

⚠️  THE `if w != r` GUARD IS A PESSIMISATION IN CPYTHON
    When w == r the write `nums[w] = nums[r]` is a self-assignment, so it is
    tempting to guard it. It loses at EVERY density (n=20000, this machine):

        density of val   plain      guarded
        0%               0.385 ms   0.558 ms   guard 45% slower
        5%               0.465 ms   0.763 ms   guard 64% slower
        50%              0.408 ms   0.625 ms   guard 53% slower
        95%              0.241 ms   0.326 ms   guard 35% slower

    Not close, and not density-dependent. The reason: the guard can only ever
    skip writes BEFORE the first occurrence of `val` — after that w < r forever
    and the branch is pure overhead. Even at 0% density, where it skips all
    1000 writes (the demo's write table proves it), the 20000 extra comparisons
    cost more than the stores they saved. A `list.__setitem__` on an int is a
    refcount bump and a pointer store; it is cheaper than the `w != r` compare
    that guards it.

    Skip the guard in Python. In C++ moving a heavyweight object, or on flash
    storage where a write costs orders of magnitude more than a compare, the
    guard is correct. Name the condition, not the rule.


================================================================================
APPROACH 2 · Fill from the back ✅✅ (the write-minimal answer)
================================================================================

    l, n = 0, len(nums)
    while l < n:
        if nums[l] == val:
            nums[l] = nums[n - 1]
            n -= 1
        else:
            l += 1
    return n

    Time O(n) · Space O(1) · MUTATES and REORDERS · writes = count(val)

STEP BY STEP for nums = [0,1,2,2,3,0,4,2], val = 2:

    l  n  nums[l]  ==val?  action                       array
    -  -  -------  ------  ---------------------------  ------------------------
    0  8     0       no    l += 1                       [0,1,2,2,3,0,4,2]
    1  8     1       no    l += 1                       [0,1,2,2,3,0,4,2]
    2  8     2      YES    nums[2] = nums[7] = 2, n=7   [0,1,2,2,3,0,4,2]
    2  7     2      YES    nums[2] = nums[6] = 4, n=6   [0,1,4,2,3,0,4,2]
    2  6     4       no    l += 1                       [0,1,4,2,3,0,4,2]
    3  6     2      YES    nums[3] = nums[5] = 0, n=5   [0,1,4,0,3,0,4,2]
    3  5     0       no    l += 1                       [0,1,4,0,3,0,4,2]
    4  5     3       no    l += 1  -> l == n, stop      [0,1,4,0,3,0,4,2]

    return 5.   nums[:5] == [0,1,4,0,3]                                      ✓
    3 writes for 3 removals. The order-preserving loop needed 5.

    Note rows 3-4: index 2 is tested TWICE. The first pull brought in another
    2 from the back. This is the whole trap.

⚠️  NEVER ADVANCE `l` AFTER PULLING FROM THE BACK
    The element you just moved into position l has never been examined. It can
    be `val` itself, so you must re-test the same index. Writing `l += 1`
    unconditionally leaves `val` sitting in the prefix you are about to return:

        [2,1,2,2,2]  val=2   correct k=1 [1]        buggy k=3 [1,2,2]  ✗
        [3,2,2,3]    val=3   correct k=2 [2,2]      buggy k=3 [2,2,3]  ✗
        [2,2,2]      val=2   correct k=0 []         buggy k=1 [2]      ✗
        [2,2,3]      val=2   correct k=1 [3]        buggy k=1 [3]      ← passes!

    That last row is why the bug survives testing: when the pulled-in value is
    NOT val, the unconditional advance is harmless, so half your test cases
    agree. The demo at the bottom runs all four. You need adjacent copies of
    `val` at the END of the array to expose it — the same lesson as the 011
    Sudoku board that failed to discriminate until the colliding digits were
    placed deliberately.

⚠️  THE LOOP CONDITION IS `l < n`, NOT `l < len(nums)`
    `n` is your own shrinking length. `len(nums)` never changes — the list keeps
    all its elements; only your notion of where the valid region ends moves.
    Using `len(nums)` re-examines the discarded tail and returns garbage.

⚠️  MINIMISING WRITES DOES NOT MINIMISE TIME (measured, n=20000)
    This is the counter-intuitive part and it is worth internalising. Measured
    at n=20000 on this machine, stable across runs:

        density of val   order-preserving   fill-from-back
        0%               0.385 ms           0.450 ms   1.2x slower
        5%               0.465 ms           0.534 ms   1.1x slower
        50%              0.408 ms           0.790 ms   1.9x SLOWER
        95%              0.241 ms           0.753 ms   3.1x SLOWER

    Fill-from-back does strictly fewer WRITES at every density below 50% — a
    quarter as many at 5% — and it is SLOWER ON THE CLOCK AT EVERY DENSITY,
    including the ones where it writes least. It never wins a single row.

    Why: both loops run exactly n iterations (each iteration either advances a
    pointer or performs a write), so the difference is entirely per-iteration
    cost. Fill-from-back's removal branch does an index load, a store and a
    decrement; the order-preserving loop's skip branch does NOTHING — it falls
    through the `if`. So as density rises, one loop gets cheaper per iteration
    and the other gets dearer, and at low density from-back is still paying for
    a `while` with two exit conditions against a C-driven `for`.

    Note what this does NOT say. Fill-from-back is not a worse algorithm; it is
    the write-minimal one, and that is a real, machine-independent property.
    What it is not is faster in CPython, where a "write" is a pointer store and
    the interpreter loop dominates everything.

    A write in CPython is a pointer store. The count only matters where a write
    is genuinely expensive: memmove of large structs, a cache line, an SSD
    erase block, a network round trip. Quote the write count as the algorithmic
    property (it is real, and it is what the interviewer is fishing for) but do
    not claim a speedup you have not measured.

⚠️  SWAP INSTEAD OF OVERWRITE, IF THE DISCARDS MATTER
        nums[l], nums[n-1] = nums[n-1], nums[l]

    Costs the same and turns the operation into a true PARTITION: the tail
    nums[k:] then contains exactly the removed elements. With the overwrite
    form the tail is arbitrary leftovers:

        [0,1,2,2,3,0,4,2] val=2  overwrite -> tail [0,4,2]   swap -> tail [2,2,2]
        [2,1,2,1,2]       val=2  overwrite -> tail [2,1,2]   swap -> tail [2,2,2]

    Here every discard equals `val`, so the tail is just `[val] * count` — not
    interesting as data. What IS interesting is that the array is now cleanly
    partitioned around an index, which is exactly the shape LC 905 and LC 75
    ask for, and exactly what quicksort's partition step produces.


================================================================================
COMPLEXITY SUMMARY
================================================================================
    Approach                 Time      Extra space  Writes       Order  Mutates?
    -----------------------  --------  -----------  -----------  -----  --------
    while val in nums:       O(n^2)    O(1)         O(n^2) moves  kept  YES
      nums.remove(val)
    [x for x in nums if...]  O(n)      O(n)         n            kept   via [:]=
    Read/write pointers ✅   O(n)      O(1)         #survivors    kept  YES
    Fill from back    ✅✅   O(n)      O(1)         count(val)    LOST  YES

    Measured write counts, n=1000 (the demo prints these):

        count(val)     survivors    read/write   fill-from-back
             0            1000        1000  *          0
            52             948         948            52
           242             758         758           242
           494             506         506           494
           760             240         240           760
          1000               0           0          1000

    * the unguarded loop still performs 1000 self-assignments when there is
      nothing to remove. Guarded, it performs 0 — and is slower anyway.

    Crossover at 50%, i.e. count(val) == survivors. Below it, fill-from-back
    writes less; above it, order-preserving writes less. Both are O(n).


================================================================================
EDGE CASES
================================================================================
    []            val=0  -> k=0
                  Empty input is explicitly allowed (0 <= nums.length). The
                  `for` loop never runs; the `while l < n` is false immediately.
                  No special-casing needed — but say that you checked.

    [1]           val=1  -> k=0, []
                  Remove the only element. Catches code that returns
                  max(1, ...) or assumes the answer is non-empty.

    [1]           val=2  -> k=1, [1]
                  Nothing to remove. Catches a loop that writes unconditionally.

    [2,2,2]       val=2  -> k=0, []
                  Everything removed. In fill-from-back, l never advances and n
                  walks down to 0 — the case where the "re-test the same index"
                  rule fires on every single iteration.

    [5,4]         val=5  -> k=1, [4]
                  Target at the FRONT. Confirms w starts at 0 here, unlike LC 26.

    [1,2,3,4,5]   val=9  -> k=5, unchanged
                  Absent value. fill-from-back does zero writes; the plain
                  read/write loop does five self-assignments.

    [2,1,2,2,2]   val=2  -> k=1, [1]
                  RUN OF val AT THE END. The only shape that catches the
                  unconditional `l += 1` bug. Every test suite for this problem
                  needs one.


================================================================================
COMMON MISTAKES
================================================================================
1. Advancing `l` after pulling from the back, leaving `val` in the prefix.
   Passes on inputs where the pulled value happens not to be `val`.

2. `while l < len(nums)` instead of `l < n`. The list never shrinks; only your
   own bound does.

3. Starting `w = 1` out of muscle memory from LC 26. The first element here has
   no special status.

4. `nums.remove(val)` in a loop — O(n^2), and if written as a `for` loop over
   the same list it also skips elements, because deletion shifts everything
   left under the iterator's index.

5. `nums = [x for x in nums if x != val]` — rebinds the local name, the caller
   sees nothing. Must be `nums[:] = ...` or element assignment.

6. Returning `len(nums)` (unchanged) or `w - 1`. `w` / `n` is already the count.

7. Tidying the tail — padding with zeroes, or `del nums[k:]`. The statement says
   the remaining elements and the size do not matter. Extra work, and `del`
   changes a length the caller was told not to depend on.

8. Comparing the whole array in your own tests. Order is not specified, so the
   only valid check is `sorted(nums[:k])` against the expected multiset. A test
   that demands `[0,1,3,0,4]` exactly will fail a correct fill-from-back
   submission.

9. Using a `set` to dedupe. Different problem — you are removing one VALUE, not
   duplicates, and multiplicity of the survivors must be preserved.


================================================================================
FOLLOW-UPS THE INTERVIEWER MAY ASK
================================================================================
Q: Minimise the number of writes.
A: Fill from the back: exactly count(val) writes, versus #survivors for the
   order-preserving loop. Crossover at 50% density. And it is legal here only
   because the statement permits reordering — in LC 26 it would be wrong.

Q: Now preserve the original order as well.
A: Then fill-from-back is out and you are back to Approach 1, #survivors
   writes. You cannot have both minimal writes and stable order in O(1) space:
   moving a survivor left past a removed slot is forced, and there are
   #survivors of them.

Q: Remove all elements in a SET of values.
A: Identical skeleton, predicate `x not in bad_set`. O(1) average per test, so
   still O(n). Do not sort the array to do it.

Q: Which elements were removed?
A: Use the swap form; then nums[k:] holds exactly the discards. Here they are
   all `val` so it is uninteresting, but the same code with a general predicate
   is a full partition — that is LC 905 and quicksort's inner step.

Q: The input is a linked list. (LC 203)
A: Easier: relink `prev.next = cur.next`. A list can actually shrink, so no
   compaction is needed. Use a dummy head so removing the first node needs no
   special case.

Q: The array is sorted, and huge.
A: Binary-search the first and last occurrence of `val`, then one memmove of
   the tail. O(log n + n) writes but a single bulk move, which on real hardware
   beats n individual stores. `list.__setitem__` with a slice does exactly this
   in C: `nums[i:j] = []`.

Q: Multithreaded / a billion elements?
A: Partition the array into chunks, compact each chunk in parallel recording
   its survivor count, prefix-sum the counts, then move each chunk's survivors
   to its final offset. Two passes, embarrassingly parallel. This is the
   standard "stream compaction" primitive on a GPU.


================================================================================
RELATED PROBLEMS — the in-place compaction / partition family
================================================================================
    LC 26   Remove Duplicates from Sorted Array — same skeleton, stateful
                                                   predicate; problem 003 here
    LC 80   Remove Duplicates II                — at most k copies
    LC 283  Move Zeroes                         — this problem with val=0 AND
                                                   order preserved; problem 005
    LC 905  Sort Array By Parity                — partition, order-agnostic:
                                                   fill-from-back verbatim
    LC 75   Sort Colors                         — three-way partition (Dutch
                                                   national flag)
    LC 203  Remove Linked List Elements         — the linked-list version
    LC 88   Merge Sorted Array                  — read/write running BACKWARDS
    LC 215  Kth Largest Element                 — quickselect, i.e. this
                                                   partition applied recursively
================================================================================
"""

import random
import timeit
from typing import List


class Solution:
    def removeElement(self, nums: List[int], val: int) -> int:
        """Fill from the back. O(n) time, O(1) space, count(val) writes.

        MUTATES and REORDERS nums. Legal because the statement permits it.
        """
        l, n = 0, len(nums)
        while l < n:
            if nums[l] == val:
                nums[l] = nums[n - 1]      # drop the last element into the hole
                n -= 1                     # ... and do NOT advance l: the value
            else:                          #     just pulled in is unexamined
                l += 1
        return n

    # ------------------------------------------------------------------
    # Alternatives.
    # ------------------------------------------------------------------
    def removeElement_stable(self, nums: List[int], val: int) -> int:
        """Order-preserving read/write pointers. #survivors writes."""
        w = 0
        for x in nums:                     # iterate values: writes land behind us
            if x != val:
                nums[w] = x
                w += 1
        return w

    def removeElement_swap(self, nums: List[int], val: int) -> int:
        """Swap form: nums[k:] ends up holding exactly the removed elements."""
        l, n = 0, len(nums)
        while l < n:
            if nums[l] == val:
                nums[l], nums[n - 1] = nums[n - 1], nums[l]
                n -= 1
            else:
                l += 1
        return n

    def removeElement_listcomp(self, nums: List[int], val: int) -> int:
        """O(n) extra space. Fastest in CPython; wrong for the in-place ask."""
        keep = [x for x in nums if x != val]
        nums[:len(keep)] = keep
        return len(keep)

    def removeElement_broken(self, nums: List[int], val: int) -> int:
        """✗ BROKEN ON PURPOSE — advances l even after pulling from the back."""
        l, n = 0, len(nums)
        while l < n:
            if nums[l] == val:
                nums[l] = nums[n - 1]
                n -= 1
            l += 1                         # BUG: unconditional
        return n


# ==============================================================================
# TESTS — run:  python 004_remove_element_solution.py
# ==============================================================================
def _stable_prefix(nums: List[int], val: int) -> List[int]:
    return [x for x in nums if x != val]


def run_tests() -> None:
    sol = Solution()
    cases = [
        ([3, 2, 2, 3], 3),
        ([0, 1, 2, 2, 3, 0, 4, 2], 2),
        ([], 0),                              # empty array
        ([1], 1),                             # remove the only element
        ([1], 2),                             # nothing to remove
        ([2, 2, 2], 2),                       # remove everything
        ([4, 5], 5),
        ([5, 4], 5),                          # target at the FRONT
        ([1, 2, 3, 4, 5], 9),                 # absent value
        ([2, 1, 2, 1, 2], 2),
        ([2, 1, 2, 2, 2], 2),                 # run of val at the END
        ([0, 0, 0, 1], 0),
        ([1, 0, 0, 0], 0),
    ]
    impls = [
        ("fill-from-back  ", sol.removeElement),
        ("order-preserving", sol.removeElement_stable),
        ("swap form       ", sol.removeElement_swap),
        ("list comp       ", sol.removeElement_listcomp),
    ]
    all_ok = True
    for name, fn in impls:
        ok = True
        for nums, val in cases:
            arr = list(nums)
            k = fn(arr, val)
            want = _stable_prefix(nums, val)
            # Order is NOT specified: compare the prefix as a multiset.
            ok &= (k == len(want) and sorted(arr[:k]) == sorted(want))
        all_ok &= ok
        print(f"{'PASS' if ok else 'FAIL'}  {name} ({len(cases)} cases)")

    # The order-preserving impl must additionally keep the original order,
    # which the multiset check above deliberately does not test.
    stable_ok = True
    for nums, val in cases:
        arr = list(nums)
        k = sol.removeElement_stable(arr, val)
        stable_ok &= arr[:k] == _stable_prefix(nums, val)
    all_ok &= stable_ok
    print(f"{'PASS' if stable_ok else 'FAIL'}  order-preserving actually preserves order")

    # ----------------------------------------------------------------------
    # Walk fill-from-back, and note whose example output it reproduces.
    # ----------------------------------------------------------------------
    print("\n--- fill-from-back walk for [0,1,2,2,3,0,4,2], val=2 ---")
    nums, val = [0, 1, 2, 2, 3, 0, 4, 2], 2
    l, n, writes = 0, len(nums), 0
    print(f"  {'l':>2} {'n':>2} {'nums[l]':>8} {'==val?':>7}  {'action':<28} array")
    while l < n:
        l0, n0, cur = l, n, nums[l]        # snapshot BEFORE mutating
        if cur == val:
            nums[l] = nums[n - 1]
            n -= 1
            writes += 1
            act = f"nums[{l0}] = nums[{n0 - 1}] = {nums[l0]}, n={n}"
        else:
            act = "l += 1"
            l += 1
        print(f"  {l0:>2} {n0:>2} {cur:>8} "
              f"{'YES' if cur == val else 'no':>7}  {act:<28} {nums}")
    print(f"  return {n}  ->  prefix {nums[:n]}   ({writes} writes)")
    print("  The order-preserving loop would have produced [0,1,3,0,4] with 5 writes.")
    print("  LeetCode's own Example 2 prints [0,1,4,0,3,_,_,_] — the fill-from-back")
    print("  output, verbatim. Their reference solution uses this algorithm.")

    # ----------------------------------------------------------------------
    # ⚠️  Advancing l unconditionally leaves `val` in the answer.
    # ----------------------------------------------------------------------
    print("\n--- ⚠️  advancing l after pulling from the back ---")
    print(f"  {'input':<26} {'val':>4}  {'correct':<20} {'buggy':<22} verdict")
    for probe, v in (([2, 1, 2, 2, 2], 2), ([3, 2, 2, 3], 3),
                     ([0, 1, 2, 2, 3, 0, 4, 2], 2), ([2, 2, 2], 2),
                     ([2, 2, 3], 2)):
        a, b = list(probe), list(probe)
        kg, kb = sol.removeElement(a, v), sol.removeElement_broken(b, v)
        good, bad = sorted(a[:kg]), sorted(b[:kb])
        if v in bad:
            verdict = "✗ val survived"
        elif kg != kb:
            verdict = "✗ wrong k"
        else:
            verdict = "passes (!)"
        print(f"  {str(probe):<26} {v:>4}  k={kg} {str(good):<16} "
              f"k={kb} {str(bad):<18} {verdict}")
    print("  Only inputs with a run of `val` at the END expose it. [2,2,3] agrees,")
    print("  so a suite without a trailing run of `val` ships the bug.")

    # ----------------------------------------------------------------------
    # Write counts: the real difference between the two algorithms.
    # ----------------------------------------------------------------------
    print("\n--- writes performed (n=1000), the crossover is at 50% ---")

    class Counting(list):
        def __init__(self, it):
            super().__init__(it)
            self.writes = 0

        def __setitem__(self, i, v):
            self.writes += 1
            super().__setitem__(i, v)

    def stable_guarded(nums, val):
        w = 0
        for r in range(len(nums)):
            if nums[r] != val:
                if w != r:
                    nums[w] = nums[r]
                w += 1
        return w

    print(f"  {'count(val)':>10} {'survivors':>10} {'read/write':>11} "
          f"{'guarded':>9} {'from-back':>10}   fewer writes")
    for density in (0.0, 0.05, 0.25, 0.5, 0.75, 1.0):
        random.seed(1)
        base = [0 if random.random() < density else random.randint(1, 50)
                for _ in range(1000)]
        cnt = base.count(0)
        out = {}
        for name, fn in (("plain", sol.removeElement_stable),
                         ("guard", stable_guarded),
                         ("back", sol.removeElement)):
            a = Counting(base)
            fn(a, 0)
            out[name] = a.writes
        winner = ("tie" if out["plain"] == out["back"]
                  else "from-back" if out["back"] < out["plain"] else "read/write")
        print(f"  {cnt:>10} {1000 - cnt:>10} {out['plain']:>11} "
              f"{out['guard']:>9} {out['back']:>10}   {winner}")
    print("  read/write writes one per SURVIVOR; from-back writes one per REMOVAL.")
    print("  The guard only saves writes before the FIRST occurrence of val —")
    print("  after that w < r forever, so it can never skip another one.")

    # ----------------------------------------------------------------------
    # ⚠️  Fewer writes is not less time. Measured, not asserted.
    # ----------------------------------------------------------------------
    print("\n--- ⚠️  wall clock, n=20000, best of 3 (this machine, now) ---")
    variants = [
        ("read/write   ", sol.removeElement_stable),
        ("+ w!=r guard ", stable_guarded),
        ("fill-from-back", sol.removeElement),
        ("list comp    ", sol.removeElement_listcomp),
    ]
    print(f"  {'density':>8}  " + "  ".join(f"{n.strip():>14}" for n, _ in variants))
    for density in (0.0, 0.05, 0.5, 0.95):
        random.seed(7)
        base = [0 if random.random() < density else random.randint(1, 50)
                for _ in range(20000)]
        row = []
        for _, fn in variants:
            best = min(timeit.repeat(lambda: fn(list(base), 0),
                                     number=5, repeat=3)) / 5
            row.append(f"{best * 1000:11.3f} ms")
        print(f"  {density:>7.0%}  " + "  ".join(f"{c:>14}" for c in row))
    print("  fill-from-back does strictly fewer WRITES below 50% density — a")
    print("  quarter as many at 5% — and yet it loses on the clock in EVERY row")
    print("  above, including the ones where it writes least. Both loops run")
    print("  exactly n iterations, so only per-iteration cost differs:")
    print("  from-back's removal branch does an index load, a store and a")
    print("  decrement; read/write's skip branch does nothing at all. Rising")
    print("  density makes one loop dearer and the other cheaper.")
    print("  The w!=r guard also loses every row: it can only skip writes before")
    print("  the first val, and 20000 extra compares cost more than 1000 stores.")
    print("  The C-level list comp wins outright — and still is not the answer,")
    print("  because it allocates O(n).")
    print("  Minimising writes is a real property; it is just not a CPython")
    print("  speedup. Quote the write count, measure the clock.")

    # ----------------------------------------------------------------------
    # ⚠️  remove()-in-a-loop is quadratic. Watch the ratio double.
    # ----------------------------------------------------------------------
    print("\n--- ⚠️  `while val in nums: nums.remove(val)` is O(n^2) ---")
    print(f"  {'n':>6} {'count':>6} {'two-pointer':>13} {'remove-loop':>14} {'ratio':>8}")

    def remove_loop(nums, val):
        while val in nums:
            nums.remove(val)
        return len(nums)

    for n_ in (2000, 4000, 8000):
        random.seed(3)
        base = [0 if random.random() < 0.5 else random.randint(1, 50)
                for _ in range(n_)]
        t1 = min(timeit.repeat(lambda: sol.removeElement_stable(list(base), 0),
                               number=20, repeat=3)) / 20
        t2 = min(timeit.repeat(lambda: remove_loop(list(base), 0),
                               number=1, repeat=3))
        print(f"  {n_:>6} {base.count(0):>6} {t1 * 1000:10.3f} ms "
              f"{t2 * 1000:11.3f} ms {t2 / t1:7.0f}x")
    print("  n doubles, the RATIO doubles: that is the fingerprint of a")
    print("  quadratic. Each .remove() scans to the target and then memmoves")
    print("  the entire tail one slot left — a full pass per removal.")

    # ----------------------------------------------------------------------
    # Overwrite vs swap: what the discarded tail holds.
    # ----------------------------------------------------------------------
    print("\n--- overwrite vs swap: the tail becomes a real partition ---")
    print(f"  {'input':<24} {'val':>3}  {'k':>2}  {'overwrite tail':<16} "
          f"{'swap tail':<14} all val?")
    for probe, v in (([0, 1, 2, 2, 3, 0, 4, 2], 2), ([3, 2, 2, 3], 3),
                     ([2, 1, 2, 1, 2], 2)):
        a, b = list(probe), list(probe)
        ka = sol.removeElement(a, v)
        kb = sol.removeElement_swap(b, v)
        print(f"  {str(probe):<24} {v:>3}  {ka:>2}  {str(a[ka:]):<16} "
              f"{str(b[kb:]):<14} {all(x == v for x in b[kb:])}")
    print("  Same cost, same prefix, but the swap form loses nothing: the array")
    print("  is now split into keepers | removed around index k. That is exactly")
    print("  LC 905, LC 75, and quicksort's partition step.")

    # ----------------------------------------------------------------------
    # ⚠️  Rebinding does not reach the caller.
    # ----------------------------------------------------------------------
    print("\n--- ⚠️  `nums = [...]` vs `nums[:] = [...]` ---")

    def rebind(nums, val):
        nums = [x for x in nums if x != val]       # LOCAL name only
        return len(nums)

    def slice_assign(nums, val):
        keep = [x for x in nums if x != val]
        nums[:len(keep)] = keep                    # writes THROUGH
        return len(keep)

    for fn, label in ((rebind, "nums = ...    "), (slice_assign, "nums[:k] = ... ")):
        arr = [3, 2, 2, 3]
        k = fn(arr, 3)
        print(f"  {label} k={k}, caller sees {arr}"
              f"{'   ✗ unchanged!' if arr == [3, 2, 2, 3] else ''}")
    print("  The grader reads the caller's array. Rebinding scores zero while")
    print("  returning the right k — the most common way to fail this problem.")

    print(f"\n{'ALL PASSED' if all_ok else 'FAILURES PRESENT'}")


if __name__ == "__main__":
    run_tests()
