// FOUNDATION LEVEL 08 - middleware, which gRPC calls INTERCEPTORS.
// The contract is deliberately boring: the lesson is entirely in the wrapping.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: interceptor.proto

package interceptorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          string                 `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"` // "ok" succeeds, "boom" makes the handler panic on purpose
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoRequest) Reset() {
	*x = DoRequest{}
	mi := &file_interceptor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoRequest) ProtoMessage() {}

func (x *DoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interceptor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoRequest.ProtoReflect.Descriptor instead.
func (*DoRequest) Descriptor() ([]byte, []int) {
	return file_interceptor_proto_rawDescGZIP(), []int{0}
}

func (x *DoRequest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

type DoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoResponse) Reset() {
	*x = DoResponse{}
	mi := &file_interceptor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoResponse) ProtoMessage() {}

func (x *DoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_interceptor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoResponse.ProtoReflect.Descriptor instead.
func (*DoResponse) Descriptor() ([]byte, []int) {
	return file_interceptor_proto_rawDescGZIP(), []int{1}
}

func (x *DoResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_interceptor_proto protoreflect.FileDescriptor

const file_interceptor_proto_rawDesc = "" +
	"\n" +
	"\x11interceptor.proto\x12\x19foundation.interceptor.v1\"\x1f\n" +
	"\tDoRequest\x12\x12\n" +
	"\x04task\x18\x01 \x01(\tR\x04task\"$\n" +
	"\n" +
	"DoResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result2Y\n" +
	"\x04Work\x12Q\n" +
	"\x02Do\x12$.foundation.interceptor.v1.DoRequest\x1a%.foundation.interceptor.v1.DoResponseBGZEdsapractice/api/gRPC/Foundation/golang/pb/interceptorpb;interceptorpbb\x06proto3"

var (
	file_interceptor_proto_rawDescOnce sync.Once
	file_interceptor_proto_rawDescData []byte
)

func file_interceptor_proto_rawDescGZIP() []byte {
	file_interceptor_proto_rawDescOnce.Do(func() {
		file_interceptor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_interceptor_proto_rawDesc), len(file_interceptor_proto_rawDesc)))
	})
	return file_interceptor_proto_rawDescData
}

var file_interceptor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_interceptor_proto_goTypes = []any{
	(*DoRequest)(nil),  // 0: foundation.interceptor.v1.DoRequest
	(*DoResponse)(nil), // 1: foundation.interceptor.v1.DoResponse
}
var file_interceptor_proto_depIdxs = []int32{
	0, // 0: foundation.interceptor.v1.Work.Do:input_type -> foundation.interceptor.v1.DoRequest
	1, // 1: foundation.interceptor.v1.Work.Do:output_type -> foundation.interceptor.v1.DoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_interceptor_proto_init() }
func file_interceptor_proto_init() {
	if File_interceptor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_interceptor_proto_rawDesc), len(file_interceptor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_interceptor_proto_goTypes,
		DependencyIndexes: file_interceptor_proto_depIdxs,
		MessageInfos:      file_interceptor_proto_msgTypes,
	}.Build()
	File_interceptor_proto = out.File
	file_interceptor_proto_goTypes = nil
	file_interceptor_proto_depIdxs = nil
}
