// FOUNDATION LEVEL 06 - gRPC status codes.
// The token/role live in the REQUEST here on purpose: metadata is level 07 and
// interceptors are levels 08-10. This level is only about the status code itself.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: statuses.proto

package statusespb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretRequest) Reset() {
	*x = GetSecretRequest{}
	mi := &file_statuses_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretRequest) ProtoMessage() {}

func (x *GetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_statuses_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretRequest.ProtoReflect.Descriptor instead.
func (*GetSecretRequest) Descriptor() ([]byte, []int) {
	return file_statuses_proto_rawDescGZIP(), []int{0}
}

func (x *GetSecretRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetSecretRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetSecretRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type Secret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_statuses_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_statuses_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_statuses_proto_rawDescGZIP(), []int{1}
}

func (x *Secret) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Secret) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_statuses_proto protoreflect.FileDescriptor

const file_statuses_proto_rawDesc = "" +
	"\n" +
	"\x0estatuses.proto\x12\x16foundation.statuses.v1\"L\n" +
	"\x10GetSecretRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\".\n" +
	"\x06Secret\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value2^\n" +
	"\x05Vault\x12U\n" +
	"\tGetSecret\x12(.foundation.statuses.v1.GetSecretRequest\x1a\x1e.foundation.statuses.v1.SecretBAZ?dsapractice/api/gRPC/Foundation/golang/pb/statusespb;statusespbb\x06proto3"

var (
	file_statuses_proto_rawDescOnce sync.Once
	file_statuses_proto_rawDescData []byte
)

func file_statuses_proto_rawDescGZIP() []byte {
	file_statuses_proto_rawDescOnce.Do(func() {
		file_statuses_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_statuses_proto_rawDesc), len(file_statuses_proto_rawDesc)))
	})
	return file_statuses_proto_rawDescData
}

var file_statuses_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_statuses_proto_goTypes = []any{
	(*GetSecretRequest)(nil), // 0: foundation.statuses.v1.GetSecretRequest
	(*Secret)(nil),           // 1: foundation.statuses.v1.Secret
}
var file_statuses_proto_depIdxs = []int32{
	0, // 0: foundation.statuses.v1.Vault.GetSecret:input_type -> foundation.statuses.v1.GetSecretRequest
	1, // 1: foundation.statuses.v1.Vault.GetSecret:output_type -> foundation.statuses.v1.Secret
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_statuses_proto_init() }
func file_statuses_proto_init() {
	if File_statuses_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_statuses_proto_rawDesc), len(file_statuses_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_statuses_proto_goTypes,
		DependencyIndexes: file_statuses_proto_depIdxs,
		MessageInfos:      file_statuses_proto_msgTypes,
	}.Build()
	File_statuses_proto = out.File
	file_statuses_proto_goTypes = nil
	file_statuses_proto_depIdxs = nil
}
