// FOUNDATION LEVEL 07 - metadata (gRPC's headers) travels BESIDE these messages,
// never inside them. Note there is no "request_id" field anywhere below.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: metaecho.proto

package metaechopb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetaEcho_Echo_FullMethodName = "/foundation.metaecho.v1.MetaEcho/Echo"
)

// MetaEchoClient is the client API for MetaEcho service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetaEchoClient interface {
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
}

type metaEchoClient struct {
	cc grpc.ClientConnInterface
}

func NewMetaEchoClient(cc grpc.ClientConnInterface) MetaEchoClient {
	return &metaEchoClient{cc}
}

func (c *metaEchoClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, MetaEcho_Echo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetaEchoServer is the server API for MetaEcho service.
// All implementations must embed UnimplementedMetaEchoServer
// for forward compatibility.
type MetaEchoServer interface {
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
	mustEmbedUnimplementedMetaEchoServer()
}

// UnimplementedMetaEchoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetaEchoServer struct{}

func (UnimplementedMetaEchoServer) Echo(context.Context, *EchoRequest) (*EchoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedMetaEchoServer) mustEmbedUnimplementedMetaEchoServer() {}
func (UnimplementedMetaEchoServer) testEmbeddedByValue()                  {}

// UnsafeMetaEchoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetaEchoServer will
// result in compilation errors.
type UnsafeMetaEchoServer interface {
	mustEmbedUnimplementedMetaEchoServer()
}

func RegisterMetaEchoServer(s grpc.ServiceRegistrar, srv MetaEchoServer) {
	// If the following call panics, it indicates UnimplementedMetaEchoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetaEcho_ServiceDesc, srv)
}

func _MetaEcho_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaEchoServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaEcho_Echo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaEchoServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetaEcho_ServiceDesc is the grpc.ServiceDesc for MetaEcho service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetaEcho_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "foundation.metaecho.v1.MetaEcho",
	HandlerType: (*MetaEchoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _MetaEcho_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metaecho.proto",
}
