"""
23 - Custom JSON & protobuf encoding - Reference Solution
=============================================================

See `23_custom_json_protobuf_encoding_explanation.py` for the full spec,
rationale, and acceptance criteria. See `event.proto` for the protobuf
schema and the exact `grpc_tools.protoc` generation command.
"""

from __future__ import annotations

import json
from collections.abc import Iterable, Iterator
from dataclasses import dataclass, field
from typing import IO, Any

# Generated by `python -m grpc_tools.protoc` from event.proto (see that
# file's header comment for the exact command). mypy has no stub/type
# information for generated protobuf modules, so the ignore is scoped to
# this one import rather than disabling mypy for the file.
import event_pb2  # type: ignore[import-untyped]


@dataclass
class Event:
    """Domain object mirrored by both the JSON encoding and `event.proto`."""

    event_id: str
    event_type: str
    timestamp: float
    payload: dict[str, Any] = field(default_factory=dict)
    priority: int = 0


# ---------------------------------------------------------------------------
# Custom JSON encode/decode.
# ---------------------------------------------------------------------------
class EventJSONEncoder(json.JSONEncoder):
    """Teaches `json.dumps` how to serialize an `Event`."""

    def default(self, o: Any) -> Any:
        if isinstance(o, Event):
            # A "__type__" marker so the decode-side object_hook can tell
            # this dict apart from an arbitrary nested dict (e.g. one
            # living inside `payload`) - object_hook sees every decoded
            # JSON object, not just top-level ones.
            return {
                "__type__": "Event",
                "event_id": o.event_id,
                "event_type": o.event_type,
                "timestamp": o.timestamp,
                "payload": o.payload,
                "priority": o.priority,
            }
        # Anything else is not ours to encode - defer to the base class,
        # which raises TypeError. Swallowing that here would silently
        # turn an encoding bug into `null` in the output.
        return super().default(o)


def event_object_hook(obj: dict[str, Any]) -> Event | dict[str, Any]:
    """`json.loads(..., object_hook=...)` callback.

    Fires bottom-up for every JSON object decoded, so a nested `payload`
    dict reaches this function before the outer `Event` dict does - only
    the `"__type__"` marker distinguishes "this is an Event" from "this
    is just a dict".
    """
    if obj.get("__type__") != "Event":
        return obj
    return Event(
        event_id=obj["event_id"],
        event_type=obj["event_type"],
        timestamp=obj["timestamp"],
        payload=obj.get("payload", {}),
        # Schema evolution: a JSON blob written before `priority` existed
        # has no such key. `.get` with a default reconstructs the field's
        # "as if it had always been 0" semantics instead of KeyError-ing.
        priority=obj.get("priority", 0),
    )


def encode_event(event: Event) -> str:
    return json.dumps(event, cls=EventJSONEncoder)


def decode_event(data: str) -> Event:
    result = json.loads(data, object_hook=event_object_hook)
    # json.loads is typed Any; the object_hook contract guarantees a
    # top-level "__type__": "Event" payload decodes to an Event, so this
    # narrows the return type for callers without a runtime cost.
    assert isinstance(result, Event)
    return result


# ---------------------------------------------------------------------------
# Streaming encode/decode over file-like objects (JSON Lines).
# ---------------------------------------------------------------------------
def write_events_jsonl(events: Iterable[Event], fp: IO[str]) -> None:
    """Streaming encode: one line per event, written as each event is
    produced. `events` may itself be a generator of unbounded length -
    this never holds more than one event's serialized JSON in memory."""
    for event in events:
        fp.write(encode_event(event) + "\n")


def read_events_jsonl(fp: IO[str]) -> Iterator[Event]:
    """Streaming decode: yields one `Event` per non-blank line of `fp`.

    A generator, not a function returning `list[Event]` - iterating `fp`
    (a file-like object) pulls one line at a time, so memory stays
    bounded to one decoded event regardless of how many lines `fp` has.
    """
    for line in fp:
        stripped = line.strip()
        if not stripped:
            continue
        yield decode_event(stripped)


# ---------------------------------------------------------------------------
# Protobuf half.
# ---------------------------------------------------------------------------
def event_to_proto(event: Event) -> event_pb2.Event:
    return event_pb2.Event(
        event_id=event.event_id,
        event_type=event.event_type,
        timestamp=event.timestamp,
        # payload is arbitrary JSON-shaped data; the .proto keeps it as a
        # string field rather than modeling it structurally, so the
        # envelope stays strongly typed without a .proto edit for every
        # new payload shape.
        payload_json=json.dumps(event.payload),
        priority=event.priority,
    )


def proto_to_event(message: event_pb2.Event) -> Event:
    return Event(
        event_id=message.event_id,
        event_type=message.event_type,
        timestamp=message.timestamp,
        payload=json.loads(message.payload_json) if message.payload_json else {},
        priority=message.priority,
    )


def encode_event_proto(event: Event) -> bytes:
    result: bytes = event_to_proto(event).SerializeToString()
    return result


def decode_event_proto(data: bytes) -> Event:
    message = event_pb2.Event()
    message.ParseFromString(data)
    return proto_to_event(message)


# ---------------------------------------------------------------------------
# Best practices
# ---------------------------------------------------------------------------
# - Mark custom-encoded types explicitly (`"__type__"`) rather than
#   guessing from shape - "does this dict have an event_id key" is a
#   landmine the moment an unrelated dict happens to share a field name.
# - Keep the `object_hook` cheap and total: it runs on *every* decoded
#   object in the document, so an expensive or partial check there costs
#   more than it looks like and can silently misclassify nested data.
# - Prefer `dict.get(key, default)` over a bare subscript anywhere you're
#   reading data that predates a field - this is the JSON-side analogue
#   of a database migration's `DEFAULT` clause, and it's the one-line
#   difference between "old data still loads" and "old data 500s".
# - Treat generated `_pb2.py`/`_pb2.pyi` files as build output: regenerate
#   from `.proto`, never hand-edit, and keep the exact `protoc` invocation
#   in a comment so it's reproducible without spelunking through CI config.
# - Keep an envelope/payload split (typed protobuf envelope, JSON payload
#   string) when only part of a message's shape is stable - it avoids a
#   .proto/codegen cycle for fields that change per event type while
#   still getting protobuf's size and type-safety wins on the routing
#   fields every consumer actually depends on.
#
# Alternative approaches
# -----------------------
# - `dataclasses.asdict`/a manual `to_dict`/`from_dict` pair instead of
#   `JSONEncoder`/`object_hook` - simpler for a single type, but doesn't
#   compose: `json.dumps` won't call a `to_dict` method on its own, so
#   every caller needs to know to call it, whereas `cls=EventJSONEncoder`
#   makes `Event` a first-class citizen of any `json.dumps` call, nested
#   inside other structures included.
# - `pydantic`'s `BaseModel.model_dump_json()`/`model_validate_json()`
#   give schema validation and JSON encode/decode together - a common
#   real-world upgrade path once you outgrow a plain dataclass, not used
#   here to stay within the curriculum's stdlib-first `json` module.
# - Protobuf's own `google.protobuf.json_format.MessageToJson`/
#   `Parse` can convert a message to/from JSON directly, useful for
#   debugging a wire-format payload without a protobuf-aware tool, but
#   sidesteps the point of this exercise (comparing two independent
#   encodings of the same domain type).
