// FOUNDATION LEVEL 11 (CAPSTONE) - one realistic schema that uses everything.
//
// Nested messages (level 02), repeated fields (level 03), presence via
// `optional` (level 04), an enum (level 05) and the evolution rules
// (level 06) all appear below. A Python program and a Go program both read
// and write the same `ShipmentFile` bytes from this one file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: l11_capstone.proto

package l11

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Carrier int32

const (
	Carrier_CARRIER_UNSPECIFIED Carrier = 0
	Carrier_CARRIER_DHL         Carrier = 1
	Carrier_CARRIER_UPS         Carrier = 2
	Carrier_CARRIER_POSTNORD    Carrier = 3
)

// Enum value maps for Carrier.
var (
	Carrier_name = map[int32]string{
		0: "CARRIER_UNSPECIFIED",
		1: "CARRIER_DHL",
		2: "CARRIER_UPS",
		3: "CARRIER_POSTNORD",
	}
	Carrier_value = map[string]int32{
		"CARRIER_UNSPECIFIED": 0,
		"CARRIER_DHL":         1,
		"CARRIER_UPS":         2,
		"CARRIER_POSTNORD":    3,
	}
)

func (x Carrier) Enum() *Carrier {
	p := new(Carrier)
	*p = x
	return p
}

func (x Carrier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Carrier) Descriptor() protoreflect.EnumDescriptor {
	return file_l11_capstone_proto_enumTypes[0].Descriptor()
}

func (Carrier) Type() protoreflect.EnumType {
	return &file_l11_capstone_proto_enumTypes[0]
}

func (x Carrier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Carrier.Descriptor instead.
func (Carrier) EnumDescriptor() ([]byte, []int) {
	return file_l11_capstone_proto_rawDescGZIP(), []int{0}
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line1         string                 `protobuf:"bytes,1,opt,name=line1,proto3" json:"line1,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	CountryCode   string                 `protobuf:"bytes,3,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_l11_capstone_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_l11_capstone_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_l11_capstone_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetLine1() string {
	if x != nil {
		return x.Line1
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

type LineItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Sku            string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Qty            int32                  `protobuf:"varint,2,opt,name=qty,proto3" json:"qty,omitempty"`
	UnitPriceCents int64                  `protobuf:"varint,3,opt,name=unit_price_cents,json=unitPriceCents,proto3" json:"unit_price_cents,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LineItem) Reset() {
	*x = LineItem{}
	mi := &file_l11_capstone_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LineItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineItem) ProtoMessage() {}

func (x *LineItem) ProtoReflect() protoreflect.Message {
	mi := &file_l11_capstone_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineItem.ProtoReflect.Descriptor instead.
func (*LineItem) Descriptor() ([]byte, []int) {
	return file_l11_capstone_proto_rawDescGZIP(), []int{1}
}

func (x *LineItem) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *LineItem) GetQty() int32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *LineItem) GetUnitPriceCents() int64 {
	if x != nil {
		return x.UnitPriceCents
	}
	return 0
}

type Shipment struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId          string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	Carrier             Carrier                `protobuf:"varint,2,opt,name=carrier,proto3,enum=found.l11.Carrier" json:"carrier,omitempty"`
	Destination         *Address               `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"` // nested message
	Items               []*LineItem            `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`             // repeated message
	Tags                []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`               // repeated scalar
	DeliveredUnixMillis *int64                 `protobuf:"varint,6,opt,name=delivered_unix_millis,json=deliveredUnixMillis,proto3,oneof" json:"delivered_unix_millis,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Shipment) Reset() {
	*x = Shipment{}
	mi := &file_l11_capstone_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shipment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shipment) ProtoMessage() {}

func (x *Shipment) ProtoReflect() protoreflect.Message {
	mi := &file_l11_capstone_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shipment.ProtoReflect.Descriptor instead.
func (*Shipment) Descriptor() ([]byte, []int) {
	return file_l11_capstone_proto_rawDescGZIP(), []int{2}
}

func (x *Shipment) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *Shipment) GetCarrier() Carrier {
	if x != nil {
		return x.Carrier
	}
	return Carrier_CARRIER_UNSPECIFIED
}

func (x *Shipment) GetDestination() *Address {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *Shipment) GetItems() []*LineItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Shipment) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Shipment) GetDeliveredUnixMillis() int64 {
	if x != nil && x.DeliveredUnixMillis != nil {
		return *x.DeliveredUnixMillis
	}
	return 0
}

// The on-disk file format: a version number plus a list of shipments. Putting
// an explicit schema_version in the payload costs one byte and tells a future
// reader which evolution step produced the file.
type ShipmentFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion int32                  `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Shipments     []*Shipment            `protobuf:"bytes,2,rep,name=shipments,proto3" json:"shipments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipmentFile) Reset() {
	*x = ShipmentFile{}
	mi := &file_l11_capstone_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentFile) ProtoMessage() {}

func (x *ShipmentFile) ProtoReflect() protoreflect.Message {
	mi := &file_l11_capstone_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentFile.ProtoReflect.Descriptor instead.
func (*ShipmentFile) Descriptor() ([]byte, []int) {
	return file_l11_capstone_proto_rawDescGZIP(), []int{3}
}

func (x *ShipmentFile) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *ShipmentFile) GetShipments() []*Shipment {
	if x != nil {
		return x.Shipments
	}
	return nil
}

var File_l11_capstone_proto protoreflect.FileDescriptor

const file_l11_capstone_proto_rawDesc = "" +
	"\n" +
	"\x12l11_capstone.proto\x12\tfound.l11\"V\n" +
	"\aAddress\x12\x14\n" +
	"\x05line1\x18\x01 \x01(\tR\x05line1\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12!\n" +
	"\fcountry_code\x18\x03 \x01(\tR\vcountryCode\"X\n" +
	"\bLineItem\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x10\n" +
	"\x03qty\x18\x02 \x01(\x05R\x03qty\x12(\n" +
	"\x10unit_price_cents\x18\x03 \x01(\x03R\x0eunitPriceCents\"\xb5\x02\n" +
	"\bShipment\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\x12,\n" +
	"\acarrier\x18\x02 \x01(\x0e2\x12.found.l11.CarrierR\acarrier\x124\n" +
	"\vdestination\x18\x03 \x01(\v2\x12.found.l11.AddressR\vdestination\x12)\n" +
	"\x05items\x18\x04 \x03(\v2\x13.found.l11.LineItemR\x05items\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x127\n" +
	"\x15delivered_unix_millis\x18\x06 \x01(\x03H\x00R\x13deliveredUnixMillis\x88\x01\x01B\x18\n" +
	"\x16_delivered_unix_millisJ\x04\b\a\x10\bR\ftracking_url\"h\n" +
	"\fShipmentFile\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\x05R\rschemaVersion\x121\n" +
	"\tshipments\x18\x02 \x03(\v2\x13.found.l11.ShipmentR\tshipments*Z\n" +
	"\aCarrier\x12\x17\n" +
	"\x13CARRIER_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vCARRIER_DHL\x10\x01\x12\x0f\n" +
	"\vCARRIER_UPS\x10\x02\x12\x14\n" +
	"\x10CARRIER_POSTNORD\x10\x03B7Z5dsapractice/api/Protobuf/Foundation/golang/pb/l11;l11b\x06proto3"

var (
	file_l11_capstone_proto_rawDescOnce sync.Once
	file_l11_capstone_proto_rawDescData []byte
)

func file_l11_capstone_proto_rawDescGZIP() []byte {
	file_l11_capstone_proto_rawDescOnce.Do(func() {
		file_l11_capstone_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_l11_capstone_proto_rawDesc), len(file_l11_capstone_proto_rawDesc)))
	})
	return file_l11_capstone_proto_rawDescData
}

var file_l11_capstone_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_l11_capstone_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_l11_capstone_proto_goTypes = []any{
	(Carrier)(0),         // 0: found.l11.Carrier
	(*Address)(nil),      // 1: found.l11.Address
	(*LineItem)(nil),     // 2: found.l11.LineItem
	(*Shipment)(nil),     // 3: found.l11.Shipment
	(*ShipmentFile)(nil), // 4: found.l11.ShipmentFile
}
var file_l11_capstone_proto_depIdxs = []int32{
	0, // 0: found.l11.Shipment.carrier:type_name -> found.l11.Carrier
	1, // 1: found.l11.Shipment.destination:type_name -> found.l11.Address
	2, // 2: found.l11.Shipment.items:type_name -> found.l11.LineItem
	3, // 3: found.l11.ShipmentFile.shipments:type_name -> found.l11.Shipment
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_l11_capstone_proto_init() }
func file_l11_capstone_proto_init() {
	if File_l11_capstone_proto != nil {
		return
	}
	file_l11_capstone_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_l11_capstone_proto_rawDesc), len(file_l11_capstone_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_l11_capstone_proto_goTypes,
		DependencyIndexes: file_l11_capstone_proto_depIdxs,
		EnumInfos:         file_l11_capstone_proto_enumTypes,
		MessageInfos:      file_l11_capstone_proto_msgTypes,
	}.Build()
	File_l11_capstone_proto = out.File
	file_l11_capstone_proto_goTypes = nil
	file_l11_capstone_proto_depIdxs = nil
}
