// FOUNDATION LEVEL 02 - a message whose field is itself a message.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: l02_nested.proto

package l02

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	CountryCode   string                 `protobuf:"bytes,3,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_l02_nested_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_l02_nested_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_l02_nested_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

type Person struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A message-typed field. Unlike a scalar, this one has real PRESENCE:
	// "no address at all" and "an address with every field empty" are
	// different states, and both languages can tell them apart.
	Home          *Address `protobuf:"bytes,2,opt,name=home,proto3" json:"home,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Person) Reset() {
	*x = Person{}
	mi := &file_l02_nested_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_l02_nested_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_l02_nested_proto_rawDescGZIP(), []int{1}
}

func (x *Person) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Person) GetHome() *Address {
	if x != nil {
		return x.Home
	}
	return nil
}

var File_l02_nested_proto protoreflect.FileDescriptor

const file_l02_nested_proto_rawDesc = "" +
	"\n" +
	"\x10l02_nested.proto\x12\tfound.l02\"X\n" +
	"\aAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12!\n" +
	"\fcountry_code\x18\x03 \x01(\tR\vcountryCode\"D\n" +
	"\x06Person\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x04home\x18\x02 \x01(\v2\x12.found.l02.AddressR\x04homeB7Z5dsapractice/api/Protobuf/Foundation/golang/pb/l02;l02b\x06proto3"

var (
	file_l02_nested_proto_rawDescOnce sync.Once
	file_l02_nested_proto_rawDescData []byte
)

func file_l02_nested_proto_rawDescGZIP() []byte {
	file_l02_nested_proto_rawDescOnce.Do(func() {
		file_l02_nested_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_l02_nested_proto_rawDesc), len(file_l02_nested_proto_rawDesc)))
	})
	return file_l02_nested_proto_rawDescData
}

var file_l02_nested_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_l02_nested_proto_goTypes = []any{
	(*Address)(nil), // 0: found.l02.Address
	(*Person)(nil),  // 1: found.l02.Person
}
var file_l02_nested_proto_depIdxs = []int32{
	0, // 0: found.l02.Person.home:type_name -> found.l02.Address
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_l02_nested_proto_init() }
func file_l02_nested_proto_init() {
	if File_l02_nested_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_l02_nested_proto_rawDesc), len(file_l02_nested_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_l02_nested_proto_goTypes,
		DependencyIndexes: file_l02_nested_proto_depIdxs,
		MessageInfos:      file_l02_nested_proto_msgTypes,
	}.Build()
	File_l02_nested_proto = out.File
	file_l02_nested_proto_goTypes = nil
	file_l02_nested_proto_depIdxs = nil
}
