// FOUNDATION LEVEL 01 (version 2 of the schema) - the "after" file.
// IDENTICAL to l01_v1.proto except that field 1 is now spelled `name`
// instead of `title`. Every field NUMBER is unchanged, so bytes encoded by
// v1 still decode perfectly here - the name never travelled.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: l01_v2.proto

package l01v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Book struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // was `title` in v1 - same number, new spelling
	Year           int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	InPrint        bool                   `protobuf:"varint,3,opt,name=in_print,json=inPrint,proto3" json:"in_print,omitempty"`
	Price          float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	CopiesSold     int64                  `protobuf:"varint,5,opt,name=copies_sold,json=copiesSold,proto3" json:"copies_sold,omitempty"`
	CoverThumbnail []byte                 `protobuf:"bytes,6,opt,name=cover_thumbnail,json=coverThumbnail,proto3" json:"cover_thumbnail,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_l01_v2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_l01_v2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_l01_v2_proto_rawDescGZIP(), []int{0}
}

func (x *Book) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Book) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Book) GetInPrint() bool {
	if x != nil {
		return x.InPrint
	}
	return false
}

func (x *Book) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Book) GetCopiesSold() int64 {
	if x != nil {
		return x.CopiesSold
	}
	return 0
}

func (x *Book) GetCoverThumbnail() []byte {
	if x != nil {
		return x.CoverThumbnail
	}
	return nil
}

var File_l01_v2_proto protoreflect.FileDescriptor

const file_l01_v2_proto_rawDesc = "" +
	"\n" +
	"\fl01_v2.proto\x12\ffound.l01.v2\"\xa9\x01\n" +
	"\x04Book\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x19\n" +
	"\bin_print\x18\x03 \x01(\bR\ainPrint\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1f\n" +
	"\vcopies_sold\x18\x05 \x01(\x03R\n" +
	"copiesSold\x12'\n" +
	"\x0fcover_thumbnail\x18\x06 \x01(\fR\x0ecoverThumbnailB;Z9dsapractice/api/Protobuf/Foundation/golang/pb/l01v2;l01v2b\x06proto3"

var (
	file_l01_v2_proto_rawDescOnce sync.Once
	file_l01_v2_proto_rawDescData []byte
)

func file_l01_v2_proto_rawDescGZIP() []byte {
	file_l01_v2_proto_rawDescOnce.Do(func() {
		file_l01_v2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_l01_v2_proto_rawDesc), len(file_l01_v2_proto_rawDesc)))
	})
	return file_l01_v2_proto_rawDescData
}

var file_l01_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_l01_v2_proto_goTypes = []any{
	(*Book)(nil), // 0: found.l01.v2.Book
}
var file_l01_v2_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_l01_v2_proto_init() }
func file_l01_v2_proto_init() {
	if File_l01_v2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_l01_v2_proto_rawDesc), len(file_l01_v2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_l01_v2_proto_goTypes,
		DependencyIndexes: file_l01_v2_proto_depIdxs,
		MessageInfos:      file_l01_v2_proto_msgTypes,
	}.Build()
	File_l01_v2_proto = out.File
	file_l01_v2_proto_goTypes = nil
	file_l01_v2_proto_depIdxs = nil
}
