# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import authz_pb2 as authz__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in authz_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReportsStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListReports = channel.unary_unary(
                '/foundation.authz.v1.Reports/ListReports',
                request_serializer=authz__pb2.ListReportsRequest.SerializeToString,
                response_deserializer=authz__pb2.ListReportsResponse.FromString,
                _registered_method=True)
        self.DeleteReport = channel.unary_unary(
                '/foundation.authz.v1.Reports/DeleteReport',
                request_serializer=authz__pb2.DeleteReportRequest.SerializeToString,
                response_deserializer=authz__pb2.DeleteReportResponse.FromString,
                _registered_method=True)


class ReportsServicer:
    """Missing associated documentation comment in .proto file."""

    def ListReports(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReportsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListReports': grpc.unary_unary_rpc_method_handler(
                    servicer.ListReports,
                    request_deserializer=authz__pb2.ListReportsRequest.FromString,
                    response_serializer=authz__pb2.ListReportsResponse.SerializeToString,
            ),
            'DeleteReport': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteReport,
                    request_deserializer=authz__pb2.DeleteReportRequest.FromString,
                    response_serializer=authz__pb2.DeleteReportResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'foundation.authz.v1.Reports', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('foundation.authz.v1.Reports', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Reports:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListReports(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/foundation.authz.v1.Reports/ListReports',
            authz__pb2.ListReportsRequest.SerializeToString,
            authz__pb2.ListReportsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/foundation.authz.v1.Reports/DeleteReport',
            authz__pb2.DeleteReportRequest.SerializeToString,
            authz__pb2.DeleteReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
