# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: authn.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'authn.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61uthn.proto\x12\x13\x66oundation.authn.v1\"\x0f\n\rWhoAmIRequest\",\n\x0eWhoAmIResponse\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t2]\n\x08Identity\x12Q\n\x06WhoAmI\x12\".foundation.authn.v1.WhoAmIRequest\x1a#.foundation.authn.v1.WhoAmIResponseB;Z9dsapractice/api/gRPC/Foundation/golang/pb/authnpb;authnpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'authn_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9dsapractice/api/gRPC/Foundation/golang/pb/authnpb;authnpb'
  _globals['_WHOAMIREQUEST']._serialized_start=36
  _globals['_WHOAMIREQUEST']._serialized_end=51
  _globals['_WHOAMIRESPONSE']._serialized_start=53
  _globals['_WHOAMIRESPONSE']._serialized_end=97
  _globals['_IDENTITY']._serialized_start=99
  _globals['_IDENTITY']._serialized_end=192
# @@protoc_insertion_point(module_scope)
