# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x12\x66oundation.chat.v1\"+\n\x0b\x43hatMessage\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t2T\n\x04\x43hat\x12L\n\x04Talk\x12\x1f.foundation.chat.v1.ChatMessage\x1a\x1f.foundation.chat.v1.ChatMessage(\x01\x30\x01\x42\x39Z7dsapractice/api/gRPC/Foundation/golang/pb/chatpb;chatpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z7dsapractice/api/gRPC/Foundation/golang/pb/chatpb;chatpb'
  _globals['_CHATMESSAGE']._serialized_start=34
  _globals['_CHATMESSAGE']._serialized_end=77
  _globals['_CHAT']._serialized_start=79
  _globals['_CHAT']._serialized_end=163
# @@protoc_insertion_point(module_scope)
