# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flaky.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'flaky.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66laky.proto\x12\x13\x66oundation.flaky.v1\"\x0e\n\x0c\x46\x65tchRequest\"0\n\rFetchResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07\x61ttempt\x18\x02 \x01(\x05\"\r\n\x0bSlowRequest\"\x1e\n\x0cSlowResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xa4\x01\n\x05\x46laky\x12N\n\x05\x46\x65tch\x12!.foundation.flaky.v1.FetchRequest\x1a\".foundation.flaky.v1.FetchResponse\x12K\n\x04Slow\x12 .foundation.flaky.v1.SlowRequest\x1a!.foundation.flaky.v1.SlowResponseB;Z9dsapractice/api/gRPC/Foundation/golang/pb/flakypb;flakypbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flaky_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9dsapractice/api/gRPC/Foundation/golang/pb/flakypb;flakypb'
  _globals['_FETCHREQUEST']._serialized_start=36
  _globals['_FETCHREQUEST']._serialized_end=50
  _globals['_FETCHRESPONSE']._serialized_start=52
  _globals['_FETCHRESPONSE']._serialized_end=100
  _globals['_SLOWREQUEST']._serialized_start=102
  _globals['_SLOWREQUEST']._serialized_end=115
  _globals['_SLOWRESPONSE']._serialized_start=117
  _globals['_SLOWRESPONSE']._serialized_end=147
  _globals['_FLAKY']._serialized_start=150
  _globals['_FLAKY']._serialized_end=314
# @@protoc_insertion_point(module_scope)
