# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: interceptor.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'interceptor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11interceptor.proto\x12\x19\x66oundation.interceptor.v1\"\x19\n\tDoRequest\x12\x0c\n\x04task\x18\x01 \x01(\t\"\x1c\n\nDoResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2Y\n\x04Work\x12Q\n\x02\x44o\x12$.foundation.interceptor.v1.DoRequest\x1a%.foundation.interceptor.v1.DoResponseBGZEdsapractice/api/gRPC/Foundation/golang/pb/interceptorpb;interceptorpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'interceptor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZEdsapractice/api/gRPC/Foundation/golang/pb/interceptorpb;interceptorpb'
  _globals['_DOREQUEST']._serialized_start=48
  _globals['_DOREQUEST']._serialized_end=73
  _globals['_DORESPONSE']._serialized_start=75
  _globals['_DORESPONSE']._serialized_end=103
  _globals['_WORK']._serialized_start=105
  _globals['_WORK']._serialized_end=194
# @@protoc_insertion_point(module_scope)
