# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orders.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'orders.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0corders.proto\x12\x14\x66oundation.orders.v1\"X\n\x12\x43reateOrderRequest\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\x12\x11\n\tgift_wrap\x18\x04 \x01(\x08\"]\n\x13\x43reateOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x13\n\x0btotal_cents\x18\x02 \x01(\x03\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\x12\r\n\x05notes\x18\x04 \x03(\t2r\n\x0cOrderService\x12\x62\n\x0b\x43reateOrder\x12(.foundation.orders.v1.CreateOrderRequest\x1a).foundation.orders.v1.CreateOrderResponseB=Z;dsapractice/api/gRPC/Foundation/golang/pb/orderspb;orderspbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orders_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z;dsapractice/api/gRPC/Foundation/golang/pb/orderspb;orderspb'
  _globals['_CREATEORDERREQUEST']._serialized_start=38
  _globals['_CREATEORDERREQUEST']._serialized_end=126
  _globals['_CREATEORDERRESPONSE']._serialized_start=128
  _globals['_CREATEORDERRESPONSE']._serialized_end=221
  _globals['_ORDERSERVICE']._serialized_start=223
  _globals['_ORDERSERVICE']._serialized_end=337
# @@protoc_insertion_point(module_scope)
