# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ping.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ping.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nping.proto\x12\x12\x66oundation.ping.v1\"\x1b\n\x0bPingRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1f\n\x0cPongResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2T\n\x07Greeter\x12I\n\x04Ping\x12\x1f.foundation.ping.v1.PingRequest\x1a .foundation.ping.v1.PongResponseB9Z7dsapractice/api/gRPC/Foundation/golang/pb/pingpb;pingpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ping_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z7dsapractice/api/gRPC/Foundation/golang/pb/pingpb;pingpb'
  _globals['_PINGREQUEST']._serialized_start=34
  _globals['_PINGREQUEST']._serialized_end=61
  _globals['_PONGRESPONSE']._serialized_start=63
  _globals['_PONGRESPONSE']._serialized_end=94
  _globals['_GREETER']._serialized_start=96
  _globals['_GREETER']._serialized_end=180
# @@protoc_insertion_point(module_scope)
