# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: statuses.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'statuses.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0estatuses.proto\x12\x16\x66oundation.statuses.v1\";\n\x10GetSecretRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\"#\n\x06Secret\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t2^\n\x05Vault\x12U\n\tGetSecret\x12(.foundation.statuses.v1.GetSecretRequest\x1a\x1e.foundation.statuses.v1.SecretBAZ?dsapractice/api/gRPC/Foundation/golang/pb/statusespb;statusespbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'statuses_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z?dsapractice/api/gRPC/Foundation/golang/pb/statusespb;statusespb'
  _globals['_GETSECRETREQUEST']._serialized_start=42
  _globals['_GETSECRETREQUEST']._serialized_end=101
  _globals['_SECRET']._serialized_start=103
  _globals['_SECRET']._serialized_end=138
  _globals['_VAULT']._serialized_start=140
  _globals['_VAULT']._serialized_end=234
# @@protoc_insertion_point(module_scope)
