# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ticker.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ticker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cticker.proto\x12\x14\x66oundation.ticker.v1\"!\n\x10\x43ountdownRequest\x12\r\n\x05start\x18\x01 \x01(\x05\"#\n\x04Tick\x12\r\n\x05value\x18\x01 \x01(\x05\x12\x0c\n\x04last\x18\x02 \x01(\x08\x32[\n\x06Ticker\x12Q\n\tCountdown\x12&.foundation.ticker.v1.CountdownRequest\x1a\x1a.foundation.ticker.v1.Tick0\x01\x42=Z;dsapractice/api/gRPC/Foundation/golang/pb/tickerpb;tickerpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ticker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z;dsapractice/api/gRPC/Foundation/golang/pb/tickerpb;tickerpb'
  _globals['_COUNTDOWNREQUEST']._serialized_start=38
  _globals['_COUNTDOWNREQUEST']._serialized_end=71
  _globals['_TICK']._serialized_start=73
  _globals['_TICK']._serialized_end=108
  _globals['_TICKER']._serialized_start=110
  _globals['_TICKER']._serialized_end=201
# @@protoc_insertion_point(module_scope)
