# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ticker_pb2 as ticker__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ticker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TickerStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Countdown = channel.unary_stream(
                '/foundation.ticker.v1.Ticker/Countdown',
                request_serializer=ticker__pb2.CountdownRequest.SerializeToString,
                response_deserializer=ticker__pb2.Tick.FromString,
                _registered_method=True)


class TickerServicer:
    """Missing associated documentation comment in .proto file."""

    def Countdown(self, request, context):
        """The "stream" keyword on the RETURN type is the entire difference between
        a unary RPC and a server-streaming one.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TickerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Countdown': grpc.unary_stream_rpc_method_handler(
                    servicer.Countdown,
                    request_deserializer=ticker__pb2.CountdownRequest.FromString,
                    response_serializer=ticker__pb2.Tick.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'foundation.ticker.v1.Ticker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('foundation.ticker.v1.Ticker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Ticker:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Countdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/foundation.ticker.v1.Ticker/Countdown',
            ticker__pb2.CountdownRequest.SerializeToString,
            ticker__pb2.Tick.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
