# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: upload.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'upload.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cupload.proto\x12\x14\x66oundation.upload.v1\"(\n\x07Reading\x12\x0e\n\x06sensor\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\"<\n\rUploadSummary\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12\x0b\n\x03sum\x18\x02 \x01(\x01\x12\x0f\n\x07\x61verage\x18\x03 \x01(\x01\x32\x62\n\x08Uploader\x12V\n\x0eUploadReadings\x12\x1d.foundation.upload.v1.Reading\x1a#.foundation.upload.v1.UploadSummary(\x01\x42=Z;dsapractice/api/gRPC/Foundation/golang/pb/uploadpb;uploadpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'upload_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z;dsapractice/api/gRPC/Foundation/golang/pb/uploadpb;uploadpb'
  _globals['_READING']._serialized_start=38
  _globals['_READING']._serialized_end=78
  _globals['_UPLOADSUMMARY']._serialized_start=80
  _globals['_UPLOADSUMMARY']._serialized_end=140
  _globals['_UPLOADER']._serialized_start=142
  _globals['_UPLOADER']._serialized_end=240
# @@protoc_insertion_point(module_scope)
